### ISSUE TITLE
FC when entering duplicates settings

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1484]
```
java.lang.NullPointerException: Attempt to write to field 'boolean eu.thedarken.sdm.duplicates.core.b.h' on a null object reference
        at eu.thedarken.sdm.duplicates.core.i.a(DuplicatesWorker.java:1060)
        at eu.thedarken.sdm.tools.k.b.b(AbstractWorker.java:216)
        at eu.thedarken.sdm.tools.k.j$b.run(WorkerHub.java:3191)
        at eu.thedarken.sdm.main.core.v.run(Unknown:1166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at eu.thedarken.sdm.main.core.q.run(Unknown:1052)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by d4rken** [comment]
Various devices and OS versions, seems to not be specific.

**Comment by d4rken** [comment]
Happens on rotation, not entering, but fixed either way 😁
