### ISSUE TITLE
Crashing during duplicates autoselection

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#1784]
Looks like a race condition with a `ConcurrentModificationException`.

```
SD Maid v4.11.0
ulefone Power_3 @ 7.1.1
```

**Comment by d4rken** [comment]
This issue has been linked to an error in Bugsnag
[**io.reactivex.exceptions.OnErrorNotImplementedException** in **eu.thedarken.sdm.main.ui.SDMMainActivity**](https://app.bugsnag.com/darken-development/sd-maid/errors/5b36b0030127030018ff4401?event_id=5b36b071e4a240001829ce2a&i=gh&m=li)

**Comment by d4rken** [comment]
```
06-30 15:42:33.390 31819-31819/eu.thedarken.sdm E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.thedarken.sdm, PID: 31819
    io.reactivex.exceptions.OnErrorNotImplementedException
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
        at io.reactivex.internal.operators.single.SingleDoFinally$DoFinallyObserver.onError(SingleDoFinally.java:81)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6642)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1084)
        at eu.thedarken.sdm.duplicates.core.autoselection.AutoSelector.doAutoselection(AutoSelector.java:47)
        at eu.thedarken.sdm.duplicates.ui.DuplicatesPresenter.lambda$doAutoSelection$8$DuplicatesPresenter(DuplicatesPresenter.java:115)
        at eu.thedarken.sdm.duplicates.ui.DuplicatesPresenter$$Lambda$10.subscribe(Unknown Source:4)
        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
        at io.reactivex.Single.subscribe(Single.java:3220)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

The worker data gets cleared while an autoselection is going on.

**Comment by d4rken** [comment]
Not really a beta bug, just a nifty race condition hitting a bug in the DuplicatesWorker.

We need to make sure we don't expose the original data structure of the worker.

**Comment by d4rken** [comment]
Hm a regression due to another fix. In <4.11.0 we didn't expose the original data structure, but also didn't prevent subscribers from modifying the returned list. 😞
