### ISSUE TITLE
TextInputEditText crashes on Meizu devices due to ROM bug

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#2303]
* https://stackoverflow.com/questions/51891415/nullpointerexception-on-meizu-devices-in-editor-updatecursorpositionmz
* https://github.com/android-in-china/Compatibility/issues/11
* https://github.com/InflationX/ViewPump

```
1549980088699 I/Debug: F: VERSIONNAME:4.13.1; VERSIONCODE:41301
1549980088700 I/Debug: P: VERSIONNAME: -- ; VERSIONCODE: -- 
49980088723 D/Debug: ro.product.flyme.model=1621
1549980088724 D/Debug: ro.product.mobile.name=m1621
1549980088724 D/Debug: ro.build.flyme.version=7
1549980088725 D/Debug: ro.product.brand=Meizu
1549980088726 D/Debug: ro.product.manufacturer=Meizu
1549980088727 D/Debug: ro.build.display.id=Flyme 7.1.5.0A
``` 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
        at android.widget.Editor.updateCursorPositionMz(Editor.java:7859)
        at android.widget.Editor.updateCursorsPositions(Editor.java:1968)
        at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5886)
        at android.widget.TextView.onDraw(TextView.java:6078)
        at android.view.View.draw(View.java:17437)
        at android.view.View.updateDisplayListIfDirty(View.java:16372)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
        at android.view.View.updateDisplayListIfDirty(View.java:16326)
        at android.view.View.draw(View.java:17183)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
        at android.view.View.draw(View.java:17449)
        at android.support.design.widget.TextInputLayout.draw(TextInputLayout.java:1577)
        at android.view.View.updateDisplayListIfDirty(View.java:16372)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
        at android.view.View.updateDisplayListIfDirty(View.java:16326)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
        at android.view.View.updateDisplayListIfDirty(View.java:16326)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
        at android.view.View.updateDisplayListIfDirty(View.java:16326)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
        at android.view.View.updateDisplayListIfDirty(View.java:16326)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
        at android.view.View.updateDisplayListIfDirty(View.java:16326)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
        at android.view.View.updateDisplayListIfDirty(View.java:16326)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
        at android.view.View.updateDisplayListIfDirty(View.java:16326)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
        at android.view.View.updateDisplayListIfDirty(View.java:16326)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:661)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:667)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:775)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3232)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3019)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2603)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1492)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7103)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:921)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:907)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6519)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
```

**Comment by d4rken** [comment]
This issue has been linked to an error in Bugsnag
[**java.lang.NullPointerException** in **eu.thedarken.sdm.main.ui.upgrades.UpgradeActivity**](https://app.bugsnag.com/darken-development/sd-maid/errors/5c62bdd7ba7569001ab763dc?event_id=5c63dc050035903598980000&i=gh&m=li)

**Comment by d4rken** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**java.lang.NullPointerException** in **eu.thedarken.sdm.main.ui.upgrades.UpgradeActivity**](https://app.bugsnag.com/darken-development/sd-maid/errors/5c62bdd7ba7569001ab763dc?event_id=5c642e410035a4ce4b250000&i=gh&m=fx)
