### ISSUE TITLE
Crash on Xiaomi devices when killing apps without root @ Android 9

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#2311]
> v4.13.1
> "androidApiLevel": "28",
> "osBuild": "PQ2A.190205.003"

```
java.lang.IllegalStateException: Bringing down ServiceRecord{69d4dfd u0 com.google.android.googlequicksearchbox/com.google.android.apps.gsa.search.core.service.SearchService} but actually running ServiceRecord{ff80868 u0 com.google.android.googlequicksearchbox/com.google.android.apps.gsa.search.core.service.SearchService}
        at android.os.Parcel.createException(Parcel.java:1958)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.app.IActivityManager$Stub$Proxy.killBackgroundProcesses(IActivityManager.java:5783)
        at android.app.ActivityManager.killBackgroundProcesses(ActivityManager.java:3607)
        at eu.thedarken.sdm.tools.c.a.b(ProcessHelper.java:110)
        at eu.thedarken.sdm.appcleaner.core.c.a(AppCleanerWorker.java:509)
        at eu.thedarken.sdm.appcleaner.core.c.a(AppCleanerWorker.java:94)
        at eu.thedarken.sdm.appcleaner.core.c.b(AppCleanerWorker.java:63)
        at eu.thedarken.sdm.main.core.c.d$b.run(WorkerHub.java:1256)
        at eu.thedarken.sdm.main.core.m.b(ThreadOverlord.java:172)
        at eu.thedarken.sdm.main.core.m.lambda$UCzb-ftGfB-qDCRT9kt9pSaX44c(Unknown)
        at eu.thedarken.sdm.main.core.-$$Lambda$m$UCzb-ftGfB-qDCRT9kt9pSaX44c.run(Unknown:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at eu.thedarken.sdm.main.core.i.a(SDMThreadFactory.java:52)
        at eu.thedarken.sdm.main.core.i.lambda$sg_s2BVNHpcqu8HbdLwr8cmfn3s(Unknown)
        at eu.thedarken.sdm.main.core.-$$Lambda$i$sg_s2BVNHpcqu8HbdLwr8cmfn3s.run(Unknown:4)
        at java.lang.Thread.run(Thread.java:764)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.bringDownServiceLocked(ActiveServices.java:2820)
	at com.android.server.am.ActiveServices.bringDownServiceIfNeededLocked(ActiveServices.java:2730)
	at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:2991)
	at com.android.server.am.ActiveServices.killServicesLocked(ActiveServices.java:3377)
	at com.android.server.am.ActivityManagerService.cleanUpApplicationRecordLocked(ActivityManagerService.java:20463)

        at unknown method(unknown file)
```

**Comment by d4rken** [comment]
This issue has been linked to an error in Bugsnag
[**java.lang.IllegalStateException** in **eu.thedarken.sdm.main.ui.SDMMainActivity**](https://app.bugsnag.com/darken-development/sd-maid/errors/5b5172350c62840018eea423?event_id=5c67da0600359f88ec2b0000&i=gh&m=li)

**Comment by d4rken** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**java.lang.IllegalStateException** in **eu.thedarken.sdm.main.ui.SDMMainActivity**](https://app.bugsnag.com/darken-development/sd-maid/errors/5b5172350c62840018eea423?event_id=5c67da0600359f88ec2b0000&i=gh&m=fx)

**Comment by d4rken** [comment]
An error linked to this issue has been reopened in Bugsnag
[**java.lang.RuntimeException** in **unknown method:0**](https://app.bugsnag.com/darken-development/sd-maid/errors/5b5172350c62840018eea423?event_id=5c708b4d0035936562840000&i=gh&m=ra)

**Comment by d4rken** [comment]
This issue has been unlinked from an error in Bugsnag
[**java.lang.RuntimeException** in **unknown method:0**](https://app.bugsnag.com/darken-development/sd-maid/errors/5b5172350c62840018eea423?event_id=5c708b4d0035936562840000&i=gh&m=ul)
