### ISSUE TITLE
Startup crash on LG-P710 (android.content.res.Resources$NotFoundException)

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#2347]
## Error in SD Maid

**java.lang.RuntimeException** in **SDMMainActivity.java:111**
Unable to start activity ComponentInfo{eu.thedarken.sdm/eu.thedarken.sdm.main.ui.SDMMainActivity}: android.view.InflateException: Binary XML file line #18: Error inflating class ImageView

[View on Bugsnag](https://app.bugsnag.com/darken-development/sd-maid/errors/5c1a5c308f17940019299f53?event_id=5c7e69390036a451ea8f0000&i=gh&m=ci)

## Stacktrace

    ActivityThread.java:2205 - android.app.ActivityThread.performLaunchActivity

[View full stacktrace](https://app.bugsnag.com/darken-development/sd-maid/errors/5c1a5c308f17940019299f53?event_id=5c7e69390036a451ea8f0000&i=gh&m=ci)

*Created by Matthias Urhahn via Bugsnag*

**Comment by d4rken** [comment]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.thedarken.sdm/eu.thedarken.sdm.main.ui.SDMMainActivity}: android.view.InflateException: Binary XML file line #18: Error inflating class ImageView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2205)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
        at android.app.ActivityThread.access$800(ActivityThread.java:142)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5118)
        at java.lang.reflect.Method.invokeNative(Method.java:-2)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
        at dalvik.system.NativeStart.main(NativeStart.java:-2)
Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class ImageView
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at eu.thedarken.sdm.main.ui.SDMMainActivity.onCreate(SDMMainActivity.java:111)
        at android.app.Activity.performCreate(Activity.java:5275)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
        at android.app.ActivityThread.access$800(ActivityThread.java:142)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5118)
        at java.lang.reflect.Method.invokeNative(Method.java:-2)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
        at dalvik.system.NativeStart.main(NativeStart.java:-2)
Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f0800a8 a=-1 r=0x7f0800a8}
        at android.content.res.Resources.loadDrawable(Resources.java:2108)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
        at android.widget.ImageView.<init>(ImageView.java:129)
        at android.support.v7.widget.AppCompatMultiAutoCompleteTextView.<init>(AppCompatImageView.java:72)
        at android.support.v7.widget.AppCompatMultiAutoCompleteTextView.<init>(AppCompatImageView.java:68)
        at android.support.v7.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:182)
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
        at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
        at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at eu.thedarken.sdm.main.ui.SDMMainActivity.onCreate(SDMMainActivity.java:111)
        at android.app.Activity.performCreate(Activity.java:5275)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
        at android.app.ActivityThread.access$800(ActivityThread.java:142)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5118)
        at java.lang.reflect.Method.invokeNative(Method.java:-2)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
        at dalvik.system.NativeStart.main(NativeStart.java:-2)
```

**Comment by d4rken** [comment]
Two affected device currently:

* LGE LG-P710 @ 4.4.2
* Sony E2115 @ 4.4.4

**Comment by d4rken** [comment]
Is the device rooted, has themes applied?

**Comment by d4rken** [comment]
Can't reproduce it on a 4.4.4 Emulator

**Comment by d4rken** [comment]
Possible fixes:

* https://stackoverflow.com/questions/28626407/android-content-res-resourcesnotfoundexception-resource-is-not-a-drawable-col
* http://karim-ouda.blogspot.com/2013/11/androidcontentresresourcesnotfoundexcep.html

**Comment by d4rken** [comment]
Hm

```
./sdmaid/build/intermediates/symbols/debug/R.txt:int drawable ic_instant_app_example 0x7f0800a8
./sdmaid/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/eu/thedarken/sdm/R.java:    public static final int ic_instant_app_example=0x7f0800a8;
```

**Comment by d4rken** [comment]
Not sure why it would try to load that, the instant apps issue was fixed on Google's side some time ago.
Theoretically I could remove that code again and it might fix the issue but fixing something without understanding it sucks :frowning:

**Comment by Dratas** [comment]
phone is LG-P710 with 4.4.2 android,properly rooted,stock rom,earlier version before this worked just fine,where i can get version before this update?

**Comment by d4rken** [comment]
Previous production(v4.12.3) or beta (v4.13.1)?

Here is a link for 4.12.3:
https://www.dropbox.com/s/tfsvmgfkdo9ecgx/SD_Maid-v4.12.3%2841203%29-RELEASE-489700d43.apk?dl=0

**Comment by Dratas** [comment]
previuos stable release,beta versions never used ☺😃

**Comment by d4rken** [comment]
There is now also beta v4.13.3 available, please try that too.

**Comment by d4rken** [comment]
https://sdmaid.darken.eu/download/beta

**Comment by Dratas** [comment]
little update beta version 4.13.3 working,4.12.3 stable working to,but 4.13.0 or wich version is between 4.13.3 beta 4.12.3 from google play just crash after start.

**Comment by d4rken** [comment]
This more or less confirms my suspicions. This is a ROM bug and while the new update doesn't include a change specific to this, it contains some changes which is enough to alter the installing process slightly such that the bug doesn't occur. So theoretically it could break on the next update again and also just be fixed again on another update.

I would also guess that by doing stuff such as uninstalling/reinstalling other apps, v4.13.2 could suddenly work for you.

I'm closing this as there is not much more I can do here. You can keep using 4.13.3.

**Comment by d4rken** [comment]
An error linked to this issue has been reopened in Bugsnag
[**java.lang.RuntimeException** in **SDMMainActivity.java:111**](https://app.bugsnag.com/darken-development/sd-maid/errors/5c1a5c308f17940019299f53?event_id=5c8017bc0036bbf3154a0000&i=gh&m=ra)

**Comment by Dratas** [comment]
looks like after last update to lastest version crashes back again :D this time even beta not helping,because from beta getting not 4.13.3 version :)

**Comment by d4rken** [comment]
So random :frowning_face:. Do you have time to try something?

Uninstall SD Maid, uninstall 3-4 other random apps, reboot, install SD Maid see if crash, if it fails, reinstall other apps, try again.

**Comment by Dratas** [comment]
just random mind,could be a sd maid pro unlocker cause these issues ?

**Comment by d4rken** [comment]
Nope, the error says it tries to find a file that isn't there. The thing is it's either in the apk or it isn't and it works on all other devicesm except for some LG devices with Android 4.4.

The only sane thing that I could think of was that I'm using some Android 4.4 incompatible code or code that triggers a bug on just this LG ROM, but it worked on v4.13.3 and doesn't work with v4.13.4  and I didn't make changes that affect this, so this is just random :astonished: ?!

**Comment by d4rken** [comment]
Here is v4.13.3 to play around with, https://www.dropbox.com/s/g7z5gikt1d9cqpr/SD_Maid-v4.13.3%2841303%29-RELEASE-05a4c75e0.apk?dl=0

**Comment by Dratas** [comment]
once i drop this chinese electronic piece into wall :D earlier 4.13.3 beta worked,now stable 4.13.3 not working :)

**Comment by d4rken** [comment]
It's the same file you got via beta the beta program :man_shrugging:

**Comment by Dratas** [comment]
now working,what i did just installed older version and updated,but not from google play,via apkupdater app ☺

**Comment by d4rken** [comment]
Still random, the source update shouldn't make a difference because it all goes through the systems apk installer.

I'm closing this again as this is something I can't fix :frowning: .
