### ISSUE TITLE
ResourceNotFoundException: Crash when scanning on LG K30

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#2348]
## Error in SD Maid

**android.content.res.Resources$NotFoundException** in **SDMMainActivity**
File res/menu/systemcleaner_menu.xml from xml type layout resource ID #0x7f0d0032

[View on Bugsnag](https://app.bugsnag.com/darken-development/sd-maid/errors/5c31851811f109001b209d93?event_id=5c7e85aa003699395ca80000&i=gh&m=ci)

## Stacktrace

    SystemCleanerFragment.java:95 - eu.thedarken.sdm.systemcleaner.ui.SystemCleanerFragment.onCreateOptionsMenuSDM
    SDMFragment.java:104 - eu.thedarken.sdm.ui.SDMFragment.onCreateOptionsMenu

[View full stacktrace](https://app.bugsnag.com/darken-development/sd-maid/errors/5c31851811f109001b209d93?event_id=5c7e85aa003699395ca80000&i=gh&m=ci)

*Created by Matthias Urhahn via Bugsnag*

**Comment by d4rken** [comment]
```
android.content.res.Resources$NotFoundException: File res/menu/systemcleaner_menu.xml from xml type layout resource ID #0x7f0d0032
        at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1189)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2149)
        at android.content.res.Resources.getLayout(Resources.java:1152)
        at android.support.v7.view.SupportMenuInflater.inflate(SupportMenuInflater.java:125)
        at eu.thedarken.sdm.systemcleaner.ui.SystemCleanerFragment.onCreateOptionsMenuSDM(SystemCleanerFragment.java:95)
        at eu.thedarken.sdm.ui.SDMFragment.onCreateOptionsMenu(SDMFragment.java:104)
        at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2561)
        at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3321)
        at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController:331)
        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:379)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at android.support.v7.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar:455)
        at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:988)
        at android.view.Choreographer.doCallbacks(Choreographer.java:800)
        at android.view.Choreographer.doFrame(Choreographer.java:732)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:974)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:175)
        at android.app.ActivityThread.main(ActivityThread.java:6724)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
Caused by: java.io.FileNotFoundException: res/menu/systemcleaner_menu.xml
        at android.content.res.AssetManager.openXmlAssetNative(AssetManager.java:-2)
        at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:552)
        at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1174)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2149)
        at android.content.res.Resources.getLayout(Resources.java:1152)
        at android.support.v7.view.SupportMenuInflater.inflate(SupportMenuInflater.java:125)
        at eu.thedarken.sdm.systemcleaner.ui.SystemCleanerFragment.onCreateOptionsMenuSDM(SystemCleanerFragment.java:95)
        at eu.thedarken.sdm.ui.SDMFragment.onCreateOptionsMenu(SDMFragment.java:104)
        at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2561)
        at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3321)
        at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController:331)
        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:379)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at android.support.v7.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar:455)
        at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:988)
        at android.view.Choreographer.doCallbacks(Choreographer.java:800)
        at android.view.Choreographer.doFrame(Choreographer.java:732)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:974)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:175)
        at android.app.ActivityThread.main(ActivityThread.java:6724)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
```

**Comment by d4rken** [comment]
There is no way this file can be not available, this is an install issue on that ROM.

**Comment by d4rken** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**android.content.res.Resources$NotFoundException** in **SDMMainActivity**](https://app.bugsnag.com/darken-development/sd-maid/errors/5c31851811f109001b209d93?event_id=5c7e85aa003699395ca80000&i=gh&m=fx)
