### ISSUE TITLE
Crash on Huawei devices when attempting to grant secondary storage access

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#2468]
```
Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
```

On Huawei devices it's possible to swap primary and secondary external storage.

This leads to `StorageVolume.createAccessIntent(...)` to return `null` instead of an `Intent`.

```
D/Setup:SAF:Presenter: Looking for access to SAFSetupStep(requests=[RequestObject(storage=Storage(location=SDCARD, path=/storage/emulated/0, userHandle=-1, flags=[SECONDARY, EMULATED], safUri=null, mount=Mountpoint(path=/storage/emulated, blockDevice=/data/media, fileSystemType=SDCARDFS, options=[noexec, reserved_mb=20, rw, fsuid=1023, nodev, fsgid=1023, nosuid, noatime, multiuser, gid=9997, mask=7])), freeSpace=12228485120)], skippable=false, result=null)
```

```
	
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1621)
	at android.app.Activity.startActivityForResult(Activity.java:4751)
	at androidx.fragment.app.d.startActivityForResult(FragmentActivity.java:767)
	at androidx.core.app.a.a(ActivityCompat.java:234)
	at androidx.fragment.app.d$a.a(FragmentActivity.java:1886)
	at androidx.fragment.app.Fragment.a(Fragment.java:13103)
	at eu.thedarken.sdm.setup.modules.saf.ui.SAFSetupFragment.a(SAFSetupFragment.kt:165)
	at eu.thedarken.sdm.setup.modules.saf.ui.c$j.a(SAFSetupPresenter.kt:1113)
	at eu.darken.mvpbakery.a.a.a(ComponentPresenter.kt:33)
	at eu.thedarken.sdm.setup.modules.saf.ui.SAFSetupFragment.onRecyclerItemClick(SAFSetupFragment.kt:1113)
	at eu.thedarken.sdm.ui.recyclerview.SDMRecyclerView.a(SDMRecyclerView.java:141)
	at eu.thedarken.sdm.ui.recyclerview.i.a(SDMRecyclerViewAdapter.java:67)
	at eu.thedarken.sdm.ui.recyclerview.j.b(SDMViewHolder.java:46)
	at eu.thedarken.sdm.ui.recyclerview.j.lambda$jPaFRAw6fPBLxGu45E4qxmgnQ1s(Unknown Source:0)
	at eu.thedarken.sdm.ui.recyclerview.-$$Lambda$j$jPaFRAw6fPBLxGu45E4qxmgnQ1s.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:6291)
	at android.view.View$PerformClick.run(View.java:24931)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

Need to catch that and fall back to manually specifying the `Intent`

**Comment by d4rken** [comment]
This issue has been linked to an error in Bugsnag
[**java.lang.NullPointerException** in **SetupActivity**](https://app.bugsnag.com/darken-development/sd-maid/errors/5ca82de5f97df80019b8808e?event_id=5cac18b00037efcda8520000&i=gh&m=li)

**Comment by d4rken** [comment]
This issue has been linked to an error in Bugsnag
[**java.lang.NullPointerException** in **SetupActivity**](https://app.bugsnag.com/darken-development/sd-maid/errors/5ca79ae624d57b0019e07613?event_id=5cac3c760037f3039a600000&i=gh&m=li)

**Comment by d4rken** [comment]
This issue has been linked to an error in Bugsnag
[**java.lang.NullPointerException** in **SetupActivity**](https://app.bugsnag.com/darken-development/sd-maid/errors/5ca89457f88501001aa6250e?event_id=5cab899d0037ede641110000&i=gh&m=li)
