### ISSUE TITLE
AppControl crashes on certain Samsung devices when retrieving shared library packages

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#3100]
Seems to affect multiple Samsung ROMs (Android 9+).

Reproducible by refreshing AppControl within SD Maid (v4.14.38+).

Triggered by `PackageManager.getSharedLibraries(...)`

```
 Package Manager Crash
 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.pm.PackageUserState.isAvailable(int)' on a null object reference
 	at com.android.server.pm.PackageManagerService.getPackagesUsingSharedLibraryLPr(PackageManagerService.java:6046)
 	at com.android.server.pm.PackageManagerService.getSharedLibraries(PackageManagerService.java:6021)
 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3049)
 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4763)
 	at android.os.Binder.execTransact(Binder.java:739)
 FATAL EXCEPTION: SDM:Thread:1
 Process: eu.thedarken.sdm, PID: 4949
 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.pm.PackageUserState.isAvailable(int)' on a null object reference
 	at android.os.Parcel.createException(Parcel.java:1972)
 	at android.os.Parcel.readException(Parcel.java:1934)
 	at android.os.Parcel.readException(Parcel.java:1884)
 	at android.content.pm.IPackageManager$Stub$Proxy.getSharedLibraries(IPackageManager.java:7904)
 	at android.app.ApplicationPackageManager.getSharedLibrariesAsUser(ApplicationPackageManager.java:596)
 	at android.app.ApplicationPackageManager.getSharedLibraries(ApplicationPackageManager.java:588)
 	at g.b.a.s.a.b.b(AppRepo.java:5)
 	at g.b.a.s.a.b.a(AppRepo.java:20)
 	at g.b.a.c.a.f.a(AppObjectFactory.java:2)
 	at g.b.a.c.a.c.c(AppControlWorker.java:34)
 	at g.b.a.j.a.d.i.a(AbstractListWorker.java:6)
 	at g.b.a.c.a.c.a(AppControlWorker.java:17)
 	at g.b.a.j.a.d.j.b(AbstractWorker.java:14)
 	at g.b.a.j.a.d.m$b.run(WorkerHub.java:4)
 	at g.b.a.j.a.G.a(ThreadOverlord.java:15)
 	at g.b.a.j.a.q.run(Unknown Source:4)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 	at g.b.a.j.a.C.a(SDMThreadFactory.java:5)
 	at g.b.a.j.a.n.run(Unknown Source:4)
 	at java.lang.Thread.run(Thread.java:764)
 Caused by: android.os.RemoteException: Remote stack trace:
 	at com.android.server.pm.PackageManagerService.getPackagesUsingSharedLibraryLPr(PackageManagerService.java:6046)
 	at com.android.server.pm.PackageManagerService.getSharedLibraries(PackageManagerService.java:6021)
 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3049)
 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4763)
 	at android.os.Binder.execTransact(Binder.java:739)
 
```

**Comment by d4rken** [comment]
https://issuetracker.google.com/issues/144513650

**Comment by d4rken** [comment]
Affected devices

![Screenshot from 2019-11-14 21-07-57](https://user-images.githubusercontent.com/1439229/68892788-06a64b00-0724-11ea-92bf-d0d4a4f491b6.png)
![Screenshot from 2019-11-14 21-07-44](https://user-images.githubusercontent.com/1439229/68892789-06a64b00-0724-11ea-91d9-1856eb02dba2.png)

**Comment by d4rken** [comment]
Also happens on:

Android 8.0.0:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.pm.PackageUserState.isAvailable(int)' on a null object reference
        at android.os.Parcel.readException(Parcel.java:1973)
        at android.os.Parcel.readException(Parcel.java:1913)
        at android.content.pm.IPackageManager$Stub$Proxy.getSharedLibraries(IPackageManager.java:7678)
        at android.app.ApplicationPackageManager.getSharedLibrariesAsUser(ApplicationPackageManager.java:622)
        at android.app.ApplicationPackageManager.getSharedLibraries(ApplicationPackageManager.java:614)
        at eu.thedarken.sdm.tools.apps.AppRepo.checkForLibraryPackages(AppRepo.java:193)
```

Android 8.1.0:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.pm.PackageUserState.isAvailable(int)' on a null object reference
        at android.os.Parcel.readException(Parcel.java:2019)
        at android.os.Parcel.readException(Parcel.java:1959)
        at android.content.pm.IPackageManager$Stub$Proxy.getSharedLibraries(IPackageManager.java:6663)
        at android.app.ApplicationPackageManager.getSharedLibrariesAsUser(ApplicationPackageManager.java:495)
        at android.app.ApplicationPackageManager.getSharedLibraries(ApplicationPackageManager.java:487)
        at eu.thedarken.sdm.tools.apps.AppRepo.checkForLibraryPackages(AppRepo.java:193)
```

![Screenshot from 2019-11-14 21-20-36](https://user-images.githubusercontent.com/1439229/68893104-b8de1280-0724-11ea-99be-fd47d4fb4f63.png)
![Screenshot from 2019-11-14 21-20-28](https://user-images.githubusercontent.com/1439229/68893105-b976a900-0724-11ea-8c96-6f6fc327c970.png)

**Comment by d4rken** [comment]
A few of the affected SM-950F devices run custom ROMs like 

[`PPR1.180610.011.hadesRom_OneUI_v11.0`](https://forum.xda-developers.com/showpost.php?p=80895989&postcount=1833)

AFAICT there are also non-custom ROMs and unrooted devices though.

**Comment by d4rken** [comment]
Bugsnag [ref](https://app.bugsnag.com/darken-development/sd-maid/errors?filters[event.since][0]=all&filters[event.message][0][type]=eq&filters[event.message][0][value]=PackageUserState)

**Comment by d4rken** [comment]
The `trichromelibrary` issue (#2987) only exists on Android 10+, so theoretically we could safely catch this and continue... Another Samsung specific workaround? :thinking:

**Comment by d4rken** [comment]
> The `trichromelibrary` issue (#2987) only exists on Android 10+, so theoretically we could safely catch this and continue... Another Samsung specific workaround?

Adding this workaround for v4.14.40. Just Samsung things :tm: ?
