### ISSUE TITLE
StackoverFlowError on Lenovo A859 devices when setting typefaces

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#3107]
Buggy lenovo ROM.

* Device: 	Lenovo A859
* ROM: `A859_ROW_S121_140518`
* Android version: 4.2.2

Not fixable.

```
Caused by: java.lang.StackOverflowError
	at java.lang.Class.getDeclaredField(Native Method)
	at java.lang.Class.getDeclaredField(Class.java:629)
	at b.i.c.i.b(TypefaceCompatBaseImpl.java:1)
	at b.i.c.i.a(TypefaceCompatBaseImpl.java:34)
	at b.i.c.c.a(TypefaceCompat.java:16)
	at b.b.g.J.setTypeface(AppCompatTextView.java:1)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypeface(TextView.java:1581)
	at b.b.g.J.setTypeface(AppCompatTextView.java:2)
	at android.widget.TextView.setTypefaceFromAttrs(TextView.java:1391)
	at android.widget.TextView.<init>(TextView.java:1300)
	at b.b.g.J.<init>(AppCompatTextView.java:3)
	at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:2)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:32)
	at b.b.a.y.onCreateView(AppCompatDelegateImpl.java:23)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:171)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
	at eu.thedarken.sdm.oneclick.OneClickFragment.a(OneClickFragment.kt:45)
	at androidx.fragment.app.Fragment.b(Fragment.java:5)
	at b.n.a.w.a(FragmentManagerImpl.java:222)
	at b.n.a.w.i(FragmentManagerImpl.java:9)
	at b.n.a.w.a(FragmentManagerImpl.java:343)
	at b.n.a.a.d(BackStackRecord.java:25)
	at b.n.a.w.a(FragmentManagerImpl.java:482)
	at b.n.a.w.c(FragmentManagerImpl.java:50)
	at b.n.a.a.c(BackStackRecord.java:12)
	at eu.thedarken.sdm.main.ui.navigation.NavigationFragment.a(NavigationFragment.kt:78)
	at g.b.a.j.b.b.q.a(NavigationPresenter.kt:4)
	at g.b.a.t.c.l.a(RxSubPresenter.kt:2)
	at h.a.e.e.d.I$a.run(ObservableObserveOn.java:23)
	at h.a.a.a.c$b.run(HandlerScheduler.java:1)
	... 9 more
```

**Comment by d4rken** [comment]
Just a note, so other devs can find it via Google. It's not you, it's lenovo :man_shrugging:
