### ISSUE TITLE
Racecondition crash on devices with physical menu button.

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#341]
On devices with a physical menubutton, if you press it close to the moment when SD Maid switches the UI into or outof it's working state, `onPrepareOptionsMenu` will be called but without inflated menu.

```
java.lang.NullPointerException
        at eu.thedarken.sdm.corpsefinder.CorpseFinderFragment.onPrepareOptionsMenu(CorpseFinderFragment.java:101)
        at android.support.v4.app.m.a(FragmentManager.java:18073)
        at android.support.v4.app.h.onPreparePanel(FragmentActivity.java:16291)
        at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:90)
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:285)
        at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:90)
        at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:567)
        at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onCreatePanelView(ToolbarActionBar.java:580)
        at android.support.v7.app.AppCompatDelegateImplV7.preparePanel(AppCompatDelegateImplV7.java:1279)
        at android.support.v7.app.AppCompatDelegateImplV7.a(AppCompatDelegateImplV7.java:12419)
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:241)
        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2071)
        at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:4020)
        at android.view.ViewRootImpl.handleImeFinishedEvent(ViewRootImpl.java:3956)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3060)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:177)
        at android.app.ActivityThread.main(ActivityThread.java:4947)
        at java.lang.reflect.Method.invokeNative(Method.java:-2)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
        at dalvik.system.NativeStart.main(NativeStart.java:-2)
```

**Comment by d4rken** [comment]
Fixed in v4.2.9
