### ISSUE TITLE
AquaMail crashes

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#354]
AquaMail likely started while the database was locked through SQL VACUUM.
Or AquaMail was running, SD Maid did suspend it, but another process was spawned that accessed it?

Likely solution will be a global exclude.

> android.database.sqlite.SQLiteException: Failed to change locale for db '/data/user/0/org.kman.AquaMail/databases/Messages.sqldb' to 'de_DE'.
	at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:395)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:220)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:195)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:468)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:190)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:182)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:876)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:856)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:754)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:579)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:568)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:263)
	at org.kman.AquaMail.data.GenericDbOpenHelper.getWritableDatabase(GenericDbOpenHelper.java:114)
	at org.kman.AquaMail.data.MailDbHelpers.getDatabase(MailDbHelpers.java:63)
	at org.kman.AquaMail.ui.AbsMessageListShard.onCreate(AbsMessageListShard.java:255)
	at org.kman.AquaMail.ui.SmartMessageListShard.onCreate(SmartMessageListShard.java:51)
	at org.kman.Compat.core.ShardFragment.onCreateWithAttach(ShardFragment.java:102)
	at org.kman.AquaMail.ui.AbsMessageListFragment.onCreate(AbsMessageListFragment.java:41)
	at android.app.Fragment.performCreate(Fragment.java:2198)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
	at android.app.BackStackRecord.run(BackStackRecord.java:793)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:168)
	at android.app.ActivityThread.main(ActivityThread.java:5781)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:557)
	at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:373)
	... 30 more

**Comment by d4rken** [comment]
Fixed in v4.1.4 with a default exclusion from all database actions.
