### ISSUE TITLE
Crash in background when documents activity is open

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#363]
```
build.board: MSM8974
build.bootloader: G900FXXU1BOJ1
build.brand: samsung
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: klte
build.display: SIXPERIENCE V7.0 - G928FXXU1AOGJ
build.fingerprint: samsung/zenltexx/zenlte:5.1.1/LMY47X/G928FXXU1AOGJ:user/release-keys
build.hardware: qcom
build.host: SWHE8815
build.id: LMY47X
build.manufacturer: samsung
build.model: SM-G900F
build.product: kltexx
build.radio: unknown
build.serial: 7772bc2a
build.tags: release-keys
build.time: 1437713832000
build.type: user
build.user: dpi
version.codename: REL
version.incremental: G928FXXU1AOGJ
version.release: 5.1.1
version.sdk_int: 22
```

When the documents activity is opened, this stops SD Maid, forcing it to save instance, and we crash on parceling?

```
04-09 16:10:46.946 I/Timeline(16152): Timeline: Activity_launch_request id:eu.thedarken.sdm time:1641255
04-09 16:10:46.966 I/PersonaManager(  984): mKnoxInfo is empty
04-09 16:10:46.976 E/Parcel  (  984): Class not found when unmarshalling: eu.thedarken.sdm.setup.SetupItem
04-09 16:10:46.976 E/Parcel  (  984): java.lang.ClassNotFoundException: eu.thedarken.sdm.setup.SetupItem
04-09 16:10:46.976 E/Parcel  (  984): 	at java.lang.Class.classForName(Native Method)
04-09 16:10:46.976 E/Parcel  (  984): 	at java.lang.Class.forName(Class.java:309)
04-09 16:10:46.976 E/Parcel  (  984): 	at java.lang.Class.forName(Class.java:273)
04-09 16:10:46.976 E/Parcel  (  984): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
04-09 16:10:46.976 E/Parcel  (  984): 	at android.os.Parcel.readParcelable(Parcel.java:2245)
04-09 16:10:46.976 E/Parcel  (  984): 	at android.os.Parcel.readValue(Parcel.java:2152)
04-09 16:10:46.976 E/Parcel  (  984): 	at android.os.Parcel.readListInternal(Parcel.java:2526)
04-09 16:10:46.976 E/Parcel  (  984): 	at android.os.Parcel.readArrayList(Parcel.java:1842)
04-09 16:10:46.976 E/Parcel  (  984): 	at android.os.Parcel.readValue(Parcel.java:2173)
04-09 16:10:46.976 E/Parcel  (  984): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
04-09 16:10:46.976 E/Parcel  (  984): 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
04-09 16:10:46.976 E/Parcel  (  984): 	at android.os.BaseBundle.getString(BaseBundle.java:918)
04-09 16:10:46.976 E/Parcel  (  984): 	at android.content.Intent.getStringExtra(Intent.java:5767)
04-09 16:10:46.976 E/Parcel  (  984): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2361)
04-09 16:10:46.976 E/Parcel  (  984): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1844)
04-09 16:10:46.976 E/Parcel  (  984): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5447)
04-09 16:10:46.976 E/Parcel  (  984): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5231)
04-09 16:10:46.976 E/Parcel  (  984): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:142)
04-09 16:10:46.976 E/Parcel  (  984): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3460)
04-09 16:10:46.976 E/Parcel  (  984): 	at android.os.Binder.execTransact(Binder.java:461)
04-09 16:10:46.976 E/Parcel  (  984): Caused by: java.lang.ClassNotFoundException: Didn't find class "eu.thedarken.sdm.setup.SetupItem" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
04-09 16:10:46.976 E/Parcel  (  984): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-09 16:10:46.976 E/Parcel  (  984): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-09 16:10:46.976 E/Parcel  (  984): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-09 16:10:46.976 E/Parcel  (  984): 	... 20 more
04-09 16:10:46.976 E/Parcel  (  984): 	Suppressed: java.lang.ClassNotFoundException: eu.thedarken.sdm.setup.SetupItem
04-09 16:10:46.976 E/Parcel  (  984): 		at java.lang.Class.classForName(Native Method)
04-09 16:10:46.976 E/Parcel  (  984): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-09 16:10:46.976 E/Parcel  (  984): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-09 16:10:46.976 E/Parcel  (  984): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-09 16:10:46.976 E/Parcel  (  984): 		... 21 more
04-09 16:10:46.976 E/Parcel  (  984): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
04-09 16:10:46.976 W/ActivityManager(  984): userId = 0, bbcId = -10000
04-09 16:10:46.976 W/ActivityManager(  984): NORMAL SET : dst_category = 1023, src_allowCategory = 0,701-1023
04-09 16:10:46.976 W/ActivityManager(  984): NORMAL SET : srcAppInfo.processName = eu.thedarken.sdm, destAppInfo.processName = eu.thedarken.sdm
04-09 16:10:46.976 D/CustomFrequencyManagerService(  984): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1958400  uid : 1000  pid : 984  pkgName : ACTIVITY_RESUME_BOOSTER@6
04-09 16:10:46.986 W/ActivityManager(  984): mDVFSHelper.acquire()
04-09 16:10:46.986 V/WindowManager(  984): addAppToken: AppWindowToken{3020f521 token=Token{d56a788 ActivityRecord{cb9972b u0 eu.thedarken.sdm/.setup.SetupActivity t1923}}} to stack=1 task=1923 at 1
```

**Comment by d4rken** [comment]
Still unclear whether this is SD Maids fault.

```
04-13 17:13:58.366 D/ActivityManager( 1040):  Launching com.android.documentsui, updated priority
04-13 17:13:58.366 V/ActivityThread( 7516): updateVisibility : ActivityRecord{2f23ae7f token=android.os.BinderProxy@319736f7 {eu.thedarken.sdm/eu.thedarken.sdm.preferences.SettingsActivity}} show : false
04-13 17:13:58.366 D/StatusBarManagerService( 1040): manageDisableList userId=0 what=0x0 pkg=Window{24cbcdc5 u0 d0 Starting com.android.documentsui}
04-13 17:13:58.376 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:58.376 D/PowerManagerService( 1040): [api] [s] userActivity : event: 0 flags: 0 (uid: 1000 pid: 1040) eventTime = 157445
04-13 17:13:58.376 D/PowerManagerService( 1040): [api] release WakeLock flags=0x2000000a tag=WindowManager uid=1000 pid=1040 (0x0)
04-13 17:13:58.376 D/PowerManagerService( 1040): [api] applyWakeLockFlagsOnReleaseLocked : userActivityNoUpdateLocked is called : SCREEN_BRIGHT_WAKE_LOCK        'WindowManager' ON_AFTER_RELEASE (uid=1000, pid=1040, ws=WorkSource{10249}) (elapsedTime=2468)
04-13 17:13:58.386 I/InjectionManager( 7891): Inside getClassLibPath caller 
04-13 17:13:58.396 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:58.396 I/SurfaceFlinger(  259): id=30 Removed TettingsAct (3/12)
04-13 17:13:58.396 I/SurfaceFlinger(  259): id=30 Removed TettingsAct (-2/12)
04-13 17:13:58.396 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:58.406 I/art     (  339): Explicit concurrent mark sweep GC freed 5(160B) AllocSpace objects, 0(0B) LOS objects, 42% free, 16MB/28MB, paused 326us total 45.350ms
04-13 17:13:58.406 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:58.416 D/OpenGLRenderer( 7516): endAllStagingAnimators on 0x9b909000 (RippleDrawable) with handle 0xa5def680
04-13 17:13:58.416 I/SurfaceFlinger(  259): id=31 Removed QersistetUr (4/11)
04-13 17:13:58.416 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:58.416 I/SurfaceFlinger(  259): id=31 Removed QersistetUr (-2/11)
04-13 17:13:58.436 I/art     (  339): Explicit concurrent mark sweep GC freed 5(160B) AllocSpace objects, 0(0B) LOS objects, 42% free, 16MB/28MB, paused 228us total 29.372ms
04-13 17:13:58.456 D/InjectionManager( 7891): InjectionManager
04-13 17:13:58.456 I/InjectionManager( 7891): featureStore :{}
04-13 17:13:58.456 D/ActivityManager( 1040): com.android.externalstorage, Starting process
04-13 17:13:58.466 E/ActivityManager( 1040): checkUser: useridlist=null, currentuser=0
04-13 17:13:58.466 E/ActivityManager( 1040): checkUser: useridlist=null, currentuser=0
04-13 17:13:58.466 E/ActivityManager( 1040): checkUser: useridlist=null, currentuser=0
04-13 17:13:58.466 E/ActivityManager( 1040): checkUser: useridlist=null, currentuser=0
04-13 17:13:58.466 D/SecWifiDisplayUtil( 7891): Metadata value : SecSettings2
04-13 17:13:58.496 E/Zygote  ( 7918): MountEmulatedStorage()
04-13 17:13:58.496 I/libpersona( 7918): KNOX_SDCARD checking this for 10010
04-13 17:13:58.496 E/Zygote  ( 7918): v2
04-13 17:13:58.496 I/libpersona( 7918): KNOX_SDCARD not a persona
04-13 17:13:58.496 I/SELinux ( 7918): Function: selinux_compare_spd_ram , priority [2] , priority version is VE=SEPF_SM-G900T_5.1.1_0017
04-13 17:13:58.496 E/SELinux ( 7918): [DEBUG] get_category: variable seinfo: platform sensitivity: NULL, cateogry: NULL
04-13 17:13:58.506 I/ActivityManager( 1040): Start proc 7918:com.android.externalstorage/u0a10 for content provider com.android.externalstorage/.ExternalStorageProvider
04-13 17:13:58.506 E/auditd  ( 2425): In denial and Property audit_ondenial is set to 1 
04-13 17:13:58.506 E/audit   ( 2425): type=1400 msg=audit(1460560438.506:697): avc:  denied  { setpgid } for  pid=339 comm="main" scontext=u:r:undefined_service:s0 tcontext=u:r:platform_app:s0 tclass=process
04-13 17:13:58.506 D/SecurityLogAgent:SEDenialService( 1040): Got Modify Event and sending Denial Intent foraudit.log
04-13 17:13:58.506 W/ContextImpl( 1040): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1752 com.android.server.SEDenialService$AuditFileObserver.onEvent:80 android.os.FileObserver$ObserverThread.onEvent:122 android.os.FileObserver$ObserverThread.observe:-2 android.os.FileObserver$ObserverThread.run:85 
04-13 17:13:58.506 E/audit   ( 2425):  SEPF_SM-G900T_5.1.1_0017
04-13 17:13:58.506 E/audit   ( 2425): type=1300 msg=audit(1460560438.506:697): arch=40000028 syscall=57 per=800000 success=yes exit=0 a0=1eee a1=153 a2=1eee a3=153 items=0 ppid=1 ppcomm=init pid=339 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="main" exe="/system/bin/app_process32_xposed" subj=u:r:undefined_service:s0 key=(null)
04-13 17:13:58.506 E/audit   ( 2425): type=1320 msg=audit(1460560438.506:697): 
04-13 17:13:58.506 D/SecurityLogAgent:SEDenialService( 1040): audit.ondenial set to 0 after sending samsung.intent.action.knox.DENIAL_NOTIFICATION intent
04-13 17:13:58.506 D/SecurityLogAgent:SEDenialService( 1040): Got Moved To Event audit.old
04-13 17:13:58.506 W/ContextImpl( 1040): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1752 com.android.server.SEDenialService$AuditFileObserver.onEvent:93 android.os.FileObserver$ObserverThread.onEvent:122 android.os.FileObserver$ObserverThread.observe:-2 android.os.FileObserver$ObserverThread.run:85 
04-13 17:13:58.506 D/SecurityLogAgent:SEDenialService( 1040): Sending Denial Intent for zip
04-13 17:13:58.506 D/SecurityLogAgent:SEDenialService( 1040): Got CLOSE_WRITE Event audit.old
04-13 17:13:58.506 D/PhoneWindow( 7891): *FMB* installDecor mIsFloating : false
04-13 17:13:58.506 D/PhoneWindow( 7891): *FMB* installDecor flags : -2139029248
04-13 17:13:58.536 I/InjectionManager( 7918): Inside getClassLibPath caller 
04-13 17:13:58.546 D/Activity( 7891): performCreate Call Injection manager
04-13 17:13:58.556 I/InjectionManager( 7891): dispatchOnViewCreated > Target : com.android.documentsui.PickFragment isFragment :true
04-13 17:13:58.556 D/AbsListView( 7891): Get MotionRecognitionManager
04-13 17:13:58.556 D/MotionRecognitionService( 1040):  ssp status : true
04-13 17:13:58.566 I/InjectionManager( 7891): dispatchOnViewCreated > Target : com.android.documentsui.RootsFragment isFragment :true
04-13 17:13:58.566 I/InjectionManager( 7891): dispatchOnViewCreated > Target : com.android.documentsui.DocumentsActivity isFragment :false
04-13 17:13:58.576 D/ExternalStorage( 7918): After updating volumes, found 1 active roots
04-13 17:13:58.576 D/InjectionManager( 7918): InjectionManager
04-13 17:13:58.576 I/InjectionManager( 7918): featureStore :{}
04-13 17:13:58.586 D/OpenGLRenderer( 7891): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
04-13 17:13:58.586 V/WindowManager( 1040): Adding window Window{68e0cbe u0 d0 com.android.documentsui/com.android.documentsui.DocumentsActivity} at 6 of 13 (before Window{24cbcdc5 u0 d0 Starting com.android.documentsui})
04-13 17:13:58.596 D/Documents( 7891): Current stack: 
04-13 17:13:58.596 D/Documents( 7891):  * null
04-13 17:13:58.596 I/ActivityManager( 1040): Killing 5979:com.sec.tcpdumpservice/1000 (adj 15): empty #22
04-13 17:13:58.596 D/PhoneWindow( 7891): *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
04-13 17:13:58.596 D/PhoneWindow( 7891): *FMB* isFloatingMenuEnabled return false
04-13 17:13:58.606 I/SurfaceFlinger(  259): id=33 createSurf (1x1),1 flag=404, EocumentsAc
04-13 17:13:58.606 D/MultiWindowConverter( 1040): dismissGuide() : Before attaching the guide view, mForceDismissGuide : false
04-13 17:13:58.606 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:58.626 D/InputDispatcher( 1040): Focus entered window: 7891
04-13 17:13:58.626 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:58.626 D/SRIB_DCS( 7891): log_dcs ThreadedRenderer::initialize entered! 
04-13 17:13:58.626 D/PointerIcon( 1040): setMouseIconStyle1 pointerType: 1001 iconType:101 flag:0 pid:1040 uid:1000
04-13 17:13:58.626 D/PointerIcon( 1040): setMouseCustomIcon IconType is same.101
04-13 17:13:58.626 I/Adreno-EGL( 7891): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
04-13 17:13:58.626 I/Adreno-EGL( 7891): OpenGL ES Shader Compiler Version: E031.25.03.06
04-13 17:13:58.626 I/Adreno-EGL( 7891): Build Date: 05/29/15 Fri
04-13 17:13:58.626 I/Adreno-EGL( 7891): Local Branch: LA.BF.1.1.1_RB1.05.01.00.042.029
04-13 17:13:58.626 I/Adreno-EGL( 7891): Remote Branch: 
04-13 17:13:58.626 I/Adreno-EGL( 7891): Local Patches: 
04-13 17:13:58.626 I/Adreno-EGL( 7891): Reconstruct Branch: 
04-13 17:13:58.626 I/OpenGLRenderer( 7891): Initialized EGL, version 1.4
04-13 17:13:58.646 D/OpenGLRenderer( 7891): Get maximum texture size. GL_MAX_TEXTURE_SIZE is 4096
04-13 17:13:58.646 D/Documents( 7891): Update found 6 roots in 194ms
04-13 17:13:58.646 D/OpenGLRenderer( 7891): Enabling debug mode 0
04-13 17:13:58.666 D/Documents( 7891): Update found 6 roots in 67ms
04-13 17:13:58.666 E/audit   ( 2425): type=1400 msg=audit(1460560438.666:698): avc:  denied  { sigchld } for  pid=339 comm="main" scontext=u:r:untrusted_app:s0 tcontext=u:r:undefined_service:s0 tclass=process
04-13 17:13:58.666 E/auditd  ( 2425): In denial and Property audit_ondenial is set to 1 
04-13 17:13:58.666 E/audit   ( 2425):  SEPF_SM-G900T_5.1.1_0017
04-13 17:13:58.666 W/ContextImpl( 1040): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1752 com.android.server.SEDenialService$AuditFileObserver.onEvent:80 android.os.FileObserver$ObserverThread.onEvent:122 android.os.FileObserver$ObserverThread.observe:-2 android.os.FileObserver$ObserverThread.run:85 
04-13 17:13:58.666 D/SecurityLogAgent:SEDenialService( 1040): Got Modify Event and sending Denial Intent foraudit.log
04-13 17:13:58.666 E/auditd  ( 2425): In denial and Property audit_ondenial is set to 1 
04-13 17:13:58.666 E/audit   ( 2425): type=1400 msg=audit(1460560438.666:698): avc:  denied  { sigchld } for  pid=339 comm="main" scontext=u:r:filtered_google_app:s0 tcontext=u:r:undefined_service:s0 tclass=process
04-13 17:13:58.666 E/audit   ( 2425):  SEPF_SM-G900T_5.1.1_0017
04-13 17:13:58.666 D/SecurityLogAgent:SEDenialService( 1040): audit.ondenial set to 0 after sending samsung.intent.action.knox.DENIAL_NOTIFICATION intent
04-13 17:13:58.666 E/auditd  ( 2425): In denial and Property audit_ondenial is set to 1 
04-13 17:13:58.666 D/SecurityLogAgent:SEDenialService( 1040): Got Modify Event and sending Denial Intent foraudit.log
04-13 17:13:58.666 W/ContextImpl( 1040): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1752 com.android.server.SEDenialService$AuditFileObserver.onEvent:80 android.os.FileObserver$ObserverThread.onEvent:122 android.os.FileObserver$ObserverThread.observe:-2 android.os.FileObserver$ObserverThread.run:85 
04-13 17:13:58.666 E/audit   ( 2425): type=1400 msg=audit(1460560438.666:698): avc:  denied  { sigchld } for  pid=339 comm="main" scontext=u:r:knox_untrusted_app:s0 tcontext=u:r:undefined_service:s0 tclass=process
04-13 17:13:58.666 E/audit   ( 2425):  SEPF_SM-G900T_5.1.1_0017
04-13 17:13:58.666 E/audit   ( 2425): type=1300 msg=audit(1460560438.666:698): arch=40000028 syscall=114 per=800000 success=yes exit=5979 a0=ffffffff a1=bec51e7c a2=1 a3=0 items=0 ppid=1 ppcomm=init pid=339 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="main" exe="/system/bin/app_process32_xposed" subj=u:r:undefined_service:s0 key=(null)
04-13 17:13:58.666 E/audit   ( 2425): type=1320 msg=audit(1460560438.666:698): 
04-13 17:13:58.666 D/SecurityLogAgent:SEDenialService( 1040): audit.ondenial set to 0 after sending samsung.intent.action.knox.DENIAL_NOTIFICATION intent
04-13 17:13:58.676 D/AbsListView( 7891): Get MotionRecognitionManager
04-13 17:13:58.676 D/AbsListView( 7891): Get MotionRecognitionManager
04-13 17:13:58.676 I/InjectionManager( 7891): dispatchOnViewCreated > Target : com.android.documentsui.RecentsCreateFragment isFragment :true
04-13 17:13:58.676 W/Documents( 7891): Failed to resolve stack: java.io.FileNotFoundException: Failed to find matching root for Root{authority=com.android.externalstorage.documents, rootId=3739-6330, title=3739-6330}
04-13 17:13:58.676 W/Documents( 7891): Failed to resolve stack: java.io.FileNotFoundException: Failed to find matching root for Root{authority=com.android.externalstorage.documents, rootId=3739-6330, title=3739-6330}
04-13 17:13:58.696 I/InjectionManager( 7891): dispatchCreateOptionsMenu :com.android.documentsui.DocumentsActivity
04-13 17:13:58.696 I/InjectionManager( 7891): dispatchCreateOptionsMenu :com.android.documentsui.RecentsCreateFragment
04-13 17:13:58.696 I/InjectionManager( 7891): dispatchPrepareOptionsMenu :com.android.documentsui.DocumentsActivity
04-13 17:13:58.696 I/InjectionManager( 7891): dispatchPrepareOptionsMenu :com.android.documentsui.RecentsCreateFragment
04-13 17:13:58.726 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:58.736 D/InputMethodManagerService( 1040): windowGainedFocus mCurrentFocusedUserId - 0 and mSecureKeypadEnabled-false
04-13 17:13:58.736 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:58.736 I/ActivityManager( 1040): Displayed Component not be shown by security: +472ms
04-13 17:13:58.736 D/CustomFrequencyManagerService( 1040): releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1958400  uid : 1000  pid : 1040  tag : ACTIVITY_RESUME_BOOSTER@6
04-13 17:13:58.736 I/Timeline( 1040): Timeline: Activity_windows_visible id: ActivityRecord{15170f37 u0 com.android.documentsui/.DocumentsActivity t2166} time:157802
04-13 17:13:58.736 W/ActivityManager( 1040): mDVFSHelper.release()
04-13 17:13:58.736 D/CustomFrequencyManagerService( 1040): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1958400  uid : 1000  pid : 1040  pkgName : ACTIVITY_RESUME_BOOSTER@10
04-13 17:13:58.736 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:58.736 D/PanelView( 1312): There is/are notification(s) 
04-13 17:13:58.786 I/Timeline( 7891): Timeline: Activity_idle id: android.os.BinderProxy@3df9db19 time:157858
04-13 17:13:58.816 V/ActivityThread( 7516): updateVisibility : ActivityRecord{26962e4c token=android.os.BinderProxy@12daeba1 {eu.thedarken.sdm/eu.thedarken.sdm.preferences.PersistetUriPermissionActivity}} show : false
04-13 17:13:58.816 W/ActivityManager( 1040): userId = 0, bbcId = -10000
04-13 17:13:58.816 W/ActivityManager( 1040): NORMAL SET : dst_category = 1023, src_allowCategory = 0,701-1023
04-13 17:13:58.816 W/ActivityManager( 1040): NORMAL SET : srcAppInfo.processName = eu.thedarken.sdm, destAppInfo.processName = ccc71.at
04-13 17:13:58.826 V/BroadcastQueue( 1040): [foreground] Process cur broadcast BroadcastRecord{1394b235 u0 ccc71.at.STOP_PACKAGE} DELIVERED for app ProcessRecord{2599423a 7565:ccc71.at/u0a192}
04-13 17:13:58.826 I/System.out( 7516): (HTTPLog)-Static: isSBSettingEnabled false
04-13 17:13:58.826 I/PersonaManager( 1040): mKnoxInfo is empty
04-13 17:13:58.826 D/ActivityManager( 1040): ccc71.at, Starting service
04-13 17:13:58.826 W/ActivityManager( 1040): userId = 0, bbcId = -10000
04-13 17:13:58.826 W/ActivityManager( 1040): NORMAL SET : dst_category = 1023, src_allowCategory = 0,701-1023
04-13 17:13:58.826 W/ActivityManager( 1040): NORMAL SET : srcAppInfo.processName = ccc71.at, destAppInfo.processName = ccc71.at
04-13 17:13:58.866 D/EnterpriseController(  281): mIsMarkChainAdded is 0 mIsBlockChainAdded is 0 netId is 0
04-13 17:13:58.866 D/Netd    (  281): getNetworkForDns: using netid 502 for uid 10249
04-13 17:13:58.876 D/++++++++( 1509): Ignoring as previous is same package
04-13 17:13:58.926 I/SurfaceFlinger(  259): id=32 Removed eocumentsui (6/11)
04-13 17:13:58.926 I/SurfaceFlinger(  259): id=32 Removed eocumentsui (-2/11)
04-13 17:13:58.926 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:58.986 I/System.out( 7516): KnoxVpnUidStorageknoxVpnSupported API value returned is false
04-13 17:13:59.036 D/CustomFrequencyManagerService( 1040): releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1958400  uid : 1000  pid : 1040  tag : ACTIVITY_RESUME_BOOSTER@10
04-13 17:13:59.136 D/AndroidRuntime( 7965): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
04-13 17:13:59.136 D/AndroidRuntime( 7965): CheckJNI is OFF
04-13 17:13:59.136 D/AndroidRuntime( 7965): readGMSProperty: start
04-13 17:13:59.136 D/AndroidRuntime( 7965): readGMSProperty: already setted!!
04-13 17:13:59.136 D/AndroidRuntime( 7965): propertySet: couldn't set property (it is from app)
04-13 17:13:59.136 D/AndroidRuntime( 7965): readGMSProperty: could not set the property(default)!!
04-13 17:13:59.136 D/AndroidRuntime( 7965): readGMSProperty: end
04-13 17:13:59.136 D/AndroidRuntime( 7965): addProductProperty: start
04-13 17:13:59.136 W/art     ( 7965): Unrecognized option -XX:debugExplicitGc=0
04-13 17:13:59.276 E/AffinityControl( 7965): AffinityControl: registerfunction enter
04-13 17:13:59.296 D/AndroidRuntime( 7965): Calling main entry com.android.commands.am.Am
04-13 17:13:59.316 V/ApplicationPolicy( 1040): isApplicationStateBlocked userId 0 pkgname eu.thedarken.sdm
04-13 17:13:59.316 I/ActivityManager( 1040): Force stopping eu.thedarken.sdm appid=10249 user=0: from pid 7965
04-13 17:13:59.316 I/PersonaManager( 1040): mKnoxInfo is empty
04-13 17:13:59.316 I/ActivityManager( 1040): Killing 7516:eu.thedarken.sdm/u0a249 (adj 7): stop eu.thedarken.sdm cause from pid 7965
04-13 17:13:59.326 W/ActivityManager( 1040): Scheduling restart of crashed service eu.thedarken.sdm/.SDMService in 1000ms
04-13 17:13:59.326 I/ActivityManager( 1040):   Force finishing activity 3 ActivityRecord{167b0001 u0 eu.thedarken.sdm/.SDMMainActivity t2166}
04-13 17:13:59.326 I/ActivityManager( 1040):   Force finishing activity 3 ActivityRecord{1916f651 u0 eu.thedarken.sdm/.preferences.SettingsActivity t2166}
04-13 17:13:59.326 I/ActivityManager( 1040):   Force finishing activity 3 ActivityRecord{20295f9d u0 eu.thedarken.sdm/.preferences.SettingsActivity t2166}
04-13 17:13:59.336 I/ActivityManager( 1040):   Force finishing activity 3 ActivityRecord{2bc7773f u0 eu.thedarken.sdm/.preferences.PersistetUriPermissionActivity t2166}
04-13 17:13:59.336 I/ActivityManager( 1040):   Force finishing activity 3 ActivityRecord{15170f37 u0 com.android.documentsui/.DocumentsActivity t2166}
04-13 17:13:59.336 D/FocusedStackFrame( 1040): Set to : 0
04-13 17:13:59.336 V/ApplicationPolicy( 1040): isApplicationStateBlocked userId 0 pkgname com.android.documentsui
04-13 17:13:59.336 V/ApplicationPolicy( 1040): isApplicationStateBlocked userId 0 pkgname com.anddoes.launcher
04-13 17:13:59.336 D/InputDispatcher( 1040): Focused application set to: xxxx
04-13 17:13:59.336 D/MultiWindowConverter( 1040): dismissGuide() : Before attaching the guide view, mForceDismissGuide : false
04-13 17:13:59.336 D/InputDispatcher( 1040): Focus left window: 7891
04-13 17:13:59.346 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:59.346 D/PointerIcon( 1040): setMouseIconStyle1 pointerType: 1001 iconType:101 flag:0 pid:1040 uid:1000
04-13 17:13:59.346 D/PointerIcon( 1040): setMouseCustomIcon IconType is same.101
04-13 17:13:59.346 I/ActivityManager( 1040): Skip updateThumbnail for r=ActivityRecord{15170f37 u0 com.android.documentsui/.DocumentsActivity t2166 f}
04-13 17:13:59.366 I/WindowState( 1040): WIN DEATH: Window{15b1042 u0 d0 eu.thedarken.sdm/eu.thedarken.sdm.preferences.SettingsActivity}
04-13 17:13:59.366 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:59.366 I/WindowState( 1040): WIN DEATH: Window{7cc81d1 u0 d0 eu.thedarken.sdm/eu.thedarken.sdm.preferences.PersistetUriPermissionActivity}
04-13 17:13:59.366 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:59.366 I/WindowState( 1040): WIN DEATH: Window{33415899 u0 d0 eu.thedarken.sdm/eu.thedarken.sdm.preferences.SettingsActivity}
04-13 17:13:59.366 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:59.376 I/WindowState( 1040): WIN DEATH: Window{16c94806 u0 d0 eu.thedarken.sdm/eu.thedarken.sdm.SDMMainActivity}
04-13 17:13:59.376 D/WindowManager( 1040): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
04-13 17:13:59.396 I/SecureStorage( 4782): [INFO]: SPID(0x00000000)Checking if this device supports Secure Storage
04-13 17:13:59.406 I/SecureStorage( 4782): [INFO]: SPID(0x00000000)This device does not support Secure Storage
04-13 17:13:59.406 D/CustomFrequencyManagerService( 1040): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1958400  uid : 1000  pid : 1040  pkgName : ACTIVITY_RESUME_BOOSTER@6
04-13 17:13:59.406 D/AndroidRuntime( 7965): Shutting down VM
```

**Comment by d4rken** [comment]
Issue was caused by `ccc71.at` (3C Toolbox).
