### ISSUE TITLE
Some exported apks can't be installed again

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#451]
Exporting and reinstalling `com.adobe.reader` fails installation with the following errors in logcat:

```
07-31 17:00:24.019 I/ActivityManager: START u0 {dat=file:///storage/emulated/0/Download/com.adobe.reader-16.2.1.apk cmp=com.android.packageinstaller/.InstallAppProgress (has extras)} from uid 10062 on display 0
07-31 17:00:24.084 I/ActivityManager: Start proc 22336:com.android.defcontainer/u0a4 for service com.android.defcontainer/.DefaultContainerService
07-31 17:00:24.169 I/ActivityManager: Displayed com.android.packageinstaller/.InstallAppProgress: +141ms
07-31 17:00:24.184 W/ResourceType: ResTable_package:unknown size 0xffffffff or headerSize 0xffff is not on an integer boundary.
07-31 17:00:24.220 I/Finsky: [1] com.google.android.vending.verifier.PackageVerificationReceiver.onReceive(2094): Skipping verification because network inactive
07-31 17:00:24.253 W/ResourceType: ResTable_package:unknown size 0xffffffff or headerSize 0xffff is not on an integer boundary.
07-31 17:00:24.256 D/DefContainer: Copying /storage/emulated/0/Download/com.adobe.reader-16.2.1.apk to base.apk
07-31 17:00:24.498 W/ResourceType: ResTable_package:unknown size 0xffffffff or headerSize 0xffff is not on an integer boundary.
07-31 17:00:24.625 W/ResourceType: ResTable_package:unknown size 0xffffffff or headerSize 0xffff is not on an integer boundary.
07-31 17:00:24.630 W/ResourceType: ResTable_package:unknown size 0xffffffff or headerSize 0xffff is not on an integer boundary.
07-31 17:00:25.395 W/PackageManager: Failed collect during installPackageLI
                                     android.content.pm.PackageParser$PackageParserException: Failed reading resources.arsc in java.util.jar.StrictJarFile@51eeb86
                                         at android.content.pm.PackageParser.loadCertificates(PackageParser.java:600)
                                         at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1103)
                                         at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1058)
                                         at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:12270)
                                         at com.android.server.pm.PackageManagerService.-wrap25(PackageManagerService.java)
                                         at com.android.server.pm.PackageManagerService$9.run(PackageManagerService.java:10170)
                                         at android.os.Handler.handleCallback(Handler.java:739)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:148)
                                         at android.os.HandlerThread.run(HandlerThread.java:61)
                                         at com.android.server.ServiceThread.run(ServiceThread.java:46)
                                      Caused by: java.lang.SecurityException: META-INF/MANIFEST.MF has invalid digest for resources.arsc in resources.arsc
                                         at java.util.jar.JarVerifier.invalidDigest(JarVerifier.java:140)
                                         at java.util.jar.JarVerifier.-wrap0(JarVerifier.java)
                                         at java.util.jar.JarVerifier$VerifierEntry.verify(JarVerifier.java:132)
                                         at java.util.jar.JarFile$JarFileInputStream.read(JarFile.java:117)
                                         at android.content.pm.PackageParser.readFullyIgnoringContents(PackageParser.java:5125)
                                         at android.content.pm.PackageParser.loadCertificates(PackageParser.java:597)
                                         at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1103) 
                                         at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1058) 
                                         at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:12270) 
                                         at com.android.server.pm.PackageManagerService.-wrap25(PackageManagerService.java) 
                                         at com.android.server.pm.PackageManagerService$9.run(PackageManagerService.java:10170) 
                                         at android.os.Handler.handleCallback(Handler.java:739) 
                                         at android.os.Handler.dispatchMessage(Handler.java:95) 
                                         at android.os.Looper.loop(Looper.java:148) 
                                         at android.os.HandlerThread.run(HandlerThread.java:61) 
                                         at com.android.server.ServiceThread.run(ServiceThread.java:46) 
07-31 17:00:25.418 I/art: Starting a blocking GC Explicit
07-31 17:00:25.419 I/ActivityManager: Killing 21178:com.android.documentsui/u0a35 (adj 15): empty #17
```

**Comment by d4rken** [comment]
This is not always reproducable but seems to be related to the busybox `cp` command.
The copied file has a different md5 checksum!?

**Comment by d4rken** [comment]
Updated busybox, issue still persists.
Only reproducable on my N5@6.0 not the N9@7.0

**Comment by d4rken** [comment]
Also happens with other busyboxes (e.g. stericons).
Doesn't happen when using the native toybox on my N5@6.0 to copy the files.

**Comment by d4rken** [comment]
Also happens with ARM binaries from:
https://busybox.net/downloads/binaries/

Additionally this is reproducable when just running the commands from `adb shell`, this does not seem to be an issue caused by SD Maid.

```
shell@hammerhead:/sdcard/bbtest $ busybox
BusyBox v1.24.2-Stericson (2016-04-23 13:23:09 EDT) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.

Usage: busybox [function [arguments]...]
   or: busybox --list[-full]
   or: busybox --install [-s] [DIR]
   or: function [arguments]...

        BusyBox is a multi-call binary that combines many common Unix
        utilities into a single executable.  Most people will create a
        link to busybox for each function they wish to use and BusyBox
        will act like whatever it was invoked as.

Currently defined functions:
        [, [[, acpid, adjtimex, arp, arping, ash, awk, base64, basename, beep,
        blkid, blockdev, brctl, bunzip2, bzcat, bzip2, cal, cat, catv, chat,
        chattr, chgrp, chmod, chown, chpst, chroot, chrt, chvt, cksum, clear,
        cmp, comm, conspy, cp, cpio, crond, crontab, cttyhack, cut, date, dc,
        dd, deallocvt, depmod, devmem, df, dhcprelay, diff, dirname, dmesg,
        dnsd, dnsdomainname, dos2unix, du, dumpkmap, dumpleases, echo, ed,
        egrep, eject, env, envdir, envuidgid, ether-wake, expand, expr,
        fakeidentd, false, fatattr, fbset, fbsplash, fdflush, fdformat, fdisk,
        fgconsole, fgrep, find, findfs, flock, fold, free, freeramdisk, fsck,
        fsck.minix, fstrim, fsync, ftpd, ftpget, ftpput, fuser, getopt, grep,
        groups, gunzip, gzip, hd, hdparm, head, hexdump, hostid, hostname,
        httpd, hush, hwclock, i2cdetect, i2cdump, i2cget, i2cset, id, ifconfig,
        ifdown, ifenslave, ifplugd, ifup, inetd, init, insmod, install, ionice,
        iostat, ip, ipaddr, ipcalc, ipcrm, ipcs, iplink, iproute, iprule,
        iptunnel, kbd_mode, kill, killall, killall5, klogd, last, less,
        linux32, linux64, linuxrc, ln, loadfont, loadkmap, logger, logname,
        logread, losetup, ls, lsattr, lsmod, lsof, lspci, lsusb, lzop, lzopcat,
        makedevs, man, md5sum, mdev, mesg, microcom, mkdir, mkdosfs, mke2fs,
        mkfifo, mkfs.ext2, mkfs.minix, mkfs.vfat, mknod, mkswap, mktemp,
        modinfo, modprobe, more, mount, mountpoint, mpstat, mt, mv, nameif,
        nanddump, nandwrite, nbd-client, nc, netstat, nice, nmeter, nohup,
        nslookup, ntpd, od, openvt, patch, pgrep, pidof, ping, ping6,
        pipe_progress, pivot_root, pkill, pmap, powertop, printenv, printf, ps,
        pscan, pstree, pwd, pwdx, raidautorun, rdate, rdev, readahead,
        readlink, readprofile, realpath, renice, reset, resize, rev, rm, rmdir,
        rmmod, route, rpm, rpm2cpio, rtcwake, run-parts, runlevel, runsv,
        runsvdir, rx, script, scriptreplay, sed, seq, setarch, setconsole,
        setfont, setkeycodes, setlogcons, setserial, setsid, setuidgid,
        sha1sum, sha256sum, sha3sum, sha512sum, showkey, shuf, slattach, sleep,
        smemcap, softlimit, sort, split, start-stop-daemon, stat, strings,
        stty, sum, sv, svlogd, swapoff, swapon, switch_root, sysctl, syslogd,
        tac, tail, tar, tcpsvd, tee, telnet, telnetd, test, tftp, tftpd, time,
        timeout, top, touch, tr, traceroute, traceroute6, true, truncate, tty,
        ttysize, tunctl, ubiattach, ubidetach, ubimkvol, ubirmvol, ubirsvol,
        ubiupdatevol, udhcpc, udhcpd, udpsvd, uevent, umount, uname, unexpand,
        uniq, unix2dos, unlink, unlzop, unxz, unzip, uptime, users, usleep,
        uudecode, uuencode, vconfig, vi, volname, wall, watch, watchdog, wc,
        wget, which, who, whoami, whois, xargs, xz, xzcat, yes, zcat, zcip

shell@hammerhead:/sdcard/bbtest $ for i in 1 2 3 4 5 6 7 8 9 0; do busybox cp /data/app/com.adobe.reader-1/base.apk $i; done
shell@hammerhead:/sdcard/bbtest $ md5sum *
29ffa3d59da19a7f02675da3ae30ce46  0
70e92a663ea983b383672aa834079b03  1
29ffa3d59da19a7f02675da3ae30ce46  2
29ffa3d59da19a7f02675da3ae30ce46  3
29ffa3d59da19a7f02675da3ae30ce46  4
29ffa3d59da19a7f02675da3ae30ce46  5
29ffa3d59da19a7f02675da3ae30ce46  6
29ffa3d59da19a7f02675da3ae30ce46  7
29ffa3d59da19a7f02675da3ae30ce46  8
29ffa3d59da19a7f02675da3ae30ce46  9
shell@hammerhead:/sdcard/bbtest $ md5sum /data/app/com.adobe.reader-1/base.apk
0af60d7f24ac35de9f519197bc31cd22  /data/app/com.adobe.reader-1/base.apk

shell@hammerhead:/sdcard/bbtest $ for i in 1 2 3 4 5 6 7 8 9 0; do busybox cp /data/app/com.adobe.reader-1/base.apk $i; done
shell@hammerhead:/sdcard/bbtest $ md5sum *
0af60d7f24ac35de9f519197bc31cd22  0
0af60d7f24ac35de9f519197bc31cd22  1
0af60d7f24ac35de9f519197bc31cd22  2
0af60d7f24ac35de9f519197bc31cd22  3
0af60d7f24ac35de9f519197bc31cd22  4
0af60d7f24ac35de9f519197bc31cd22  5
0af60d7f24ac35de9f519197bc31cd22  6
0af60d7f24ac35de9f519197bc31cd22  7
0af60d7f24ac35de9f519197bc31cd22  8
0af60d7f24ac35de9f519197bc31cd22  9

shell@hammerhead:/sdcard/bbtest $ for i in 1 2 3 4 5 6 7 8 9 0; do busybox cp /data/app/stericson.busybox-1/base.apk $i; done
shell@hammerhead:/sdcard/bbtest $ md5sum *
7abf6b3df474c36f96ac0d4274c414ed  0
7abf6b3df474c36f96ac0d4274c414ed  1
7abf6b3df474c36f96ac0d4274c414ed  2
7abf6b3df474c36f96ac0d4274c414ed  3
7abf6b3df474c36f96ac0d4274c414ed  4
7abf6b3df474c36f96ac0d4274c414ed  5
7abf6b3df474c36f96ac0d4274c414ed  6
7abf6b3df474c36f96ac0d4274c414ed  7
7abf6b3df474c36f96ac0d4274c414ed  8
7abf6b3df474c36f96ac0d4274c414ed  9
shell@hammerhead:/sdcard/bbtest $ md5sum /data/app/stericson.busybox-1/base.apk
a62c6fc09fecac7105023ca0db4d7b35  /data/app/stericson.busybox-1/base.apk

shell@hammerhead:/sdcard/bbtest $ for i in 1 2 3 4 5 6 7 8 9 0; do busybox cp /data/app/stericson.busybox-1/base.apk $i; done
shell@hammerhead:/sdcard/bbtest $ md5sum *
a62c6fc09fecac7105023ca0db4d7b35  0
a62c6fc09fecac7105023ca0db4d7b35  1
a62c6fc09fecac7105023ca0db4d7b35  2
a62c6fc09fecac7105023ca0db4d7b35  3
a62c6fc09fecac7105023ca0db4d7b35  4
a62c6fc09fecac7105023ca0db4d7b35  5
a62c6fc09fecac7105023ca0db4d7b35  6
a62c6fc09fecac7105023ca0db4d7b35  7
a62c6fc09fecac7105023ca0db4d7b35  8
a62c6fc09fecac7105023ca0db4d7b35  9
shell@hammerhead:/sdcard/bbtest $ md5sum /data/app/stericson.busybox-1/base.apk
a62c6fc09fecac7105023ca0db4d7b35  /data/app/stericson.busybox-1/base.apk
```

**Comment by d4rken** [comment]
```
shell@hammerhead:/sdcard/bbtest $ for i in 1 2 3 4 5 6 7 8 9 0; do busybox cp /data/app/com.adobe.reader-1/base.apk $i; done
shell@hammerhead:/sdcard/bbtest $ md5sum *
801c5952227a36e32689e8b5fc9bf384  0
199632c59a851d85b4a84beadd90c3c4  1
801c5952227a36e32689e8b5fc9bf384  2
801c5952227a36e32689e8b5fc9bf384  3
801c5952227a36e32689e8b5fc9bf384  4
801c5952227a36e32689e8b5fc9bf384  5
801c5952227a36e32689e8b5fc9bf384  6
801c5952227a36e32689e8b5fc9bf384  7
801c5952227a36e32689e8b5fc9bf384  8
801c5952227a36e32689e8b5fc9bf384  9
shell@hammerhead:/sdcard/bbtest $ ls -la
-rw-rw---- root     sdcard_rw 12789573 2016-08-03 21:45 0
-rw-rw---- root     sdcard_rw 12789573 2016-08-03 21:45 1
-rw-rw---- root     sdcard_rw 12789573 2016-08-03 21:45 2
-rw-rw---- root     sdcard_rw 12789573 2016-08-03 21:45 3
-rw-rw---- root     sdcard_rw 12789573 2016-08-03 21:45 4
-rw-rw---- root     sdcard_rw 12789573 2016-08-03 21:45 5
-rw-rw---- root     sdcard_rw 12789573 2016-08-03 21:45 6
-rw-rw---- root     sdcard_rw 12789573 2016-08-03 21:45 7
-rw-rw---- root     sdcard_rw 12789573 2016-08-03 21:45 8
-rw-rw---- root     sdcard_rw 12789573 2016-08-03 21:45 9
shell@hammerhead:/sdcard/bbtest $ for i in 1 2 3 4 5 6 7 8 9 0; do busybox cp /data/app/com.adobe.reader-1/base.apk a$i; done
shell@hammerhead:/sdcard/bbtest $ md5sum *
801c5952227a36e32689e8b5fc9bf384  0
199632c59a851d85b4a84beadd90c3c4  1
801c5952227a36e32689e8b5fc9bf384  2
801c5952227a36e32689e8b5fc9bf384  3
801c5952227a36e32689e8b5fc9bf384  4
801c5952227a36e32689e8b5fc9bf384  5
801c5952227a36e32689e8b5fc9bf384  6
801c5952227a36e32689e8b5fc9bf384  7
801c5952227a36e32689e8b5fc9bf384  8
801c5952227a36e32689e8b5fc9bf384  9
801c5952227a36e32689e8b5fc9bf384  a0
801c5952227a36e32689e8b5fc9bf384  a1
801c5952227a36e32689e8b5fc9bf384  a2
199632c59a851d85b4a84beadd90c3c4  a3
801c5952227a36e32689e8b5fc9bf384  a4
801c5952227a36e32689e8b5fc9bf384  a5
801c5952227a36e32689e8b5fc9bf384  a6
801c5952227a36e32689e8b5fc9bf384  a7
801c5952227a36e32689e8b5fc9bf384  a8
801c5952227a36e32689e8b5fc9bf384  a9
shell@hammerhead:/sdcard/bbtest $ for i in 1 2 3 4 5 6 7 8 9 0; do busybox cp /data/app/com.adobe.reader-1/base.apk b$i; done
shell@hammerhead:/sdcard/bbtest $ md5sum *
801c5952227a36e32689e8b5fc9bf384  0
199632c59a851d85b4a84beadd90c3c4  1
801c5952227a36e32689e8b5fc9bf384  2
801c5952227a36e32689e8b5fc9bf384  3
801c5952227a36e32689e8b5fc9bf384  4
801c5952227a36e32689e8b5fc9bf384  5
801c5952227a36e32689e8b5fc9bf384  6
801c5952227a36e32689e8b5fc9bf384  7
801c5952227a36e32689e8b5fc9bf384  8
801c5952227a36e32689e8b5fc9bf384  9
801c5952227a36e32689e8b5fc9bf384  a0
801c5952227a36e32689e8b5fc9bf384  a1
801c5952227a36e32689e8b5fc9bf384  a2
199632c59a851d85b4a84beadd90c3c4  a3
801c5952227a36e32689e8b5fc9bf384  a4
801c5952227a36e32689e8b5fc9bf384  a5
801c5952227a36e32689e8b5fc9bf384  a6
801c5952227a36e32689e8b5fc9bf384  a7
801c5952227a36e32689e8b5fc9bf384  a8
801c5952227a36e32689e8b5fc9bf384  a9
52fbd38e5029a87b87db67e90ac4c294  b0
a9990d6eabf5a319071c4b71c3ea0731  b1
cb76902789d4b4bac7f834bb6fa1e577  b2
dc768c6a70f79bc35a27cdd0ff198db6  b3
52fbd38e5029a87b87db67e90ac4c294  b4
52fbd38e5029a87b87db67e90ac4c294  b5
52fbd38e5029a87b87db67e90ac4c294  b6
52fbd38e5029a87b87db67e90ac4c294  b7
52fbd38e5029a87b87db67e90ac4c294  b8
52fbd38e5029a87b87db67e90ac4c294  b9
shell@hammerhead:/sdcard/bbtest $
shell@hammerhead:/sdcard/bbtest $ for i in 1 2 3 4 5 6 7 8 9 0; do toybox cp /data/app/com.adobe.reader-1/base.apk
shell@hammerhead:/sdcard/bbtest $ md5sum *
801c5952227a36e32689e8b5fc9bf384  0
199632c59a851d85b4a84beadd90c3c4  1
801c5952227a36e32689e8b5fc9bf384  2
801c5952227a36e32689e8b5fc9bf384  3
801c5952227a36e32689e8b5fc9bf384  4
801c5952227a36e32689e8b5fc9bf384  5
801c5952227a36e32689e8b5fc9bf384  6
801c5952227a36e32689e8b5fc9bf384  7
801c5952227a36e32689e8b5fc9bf384  8
801c5952227a36e32689e8b5fc9bf384  9
801c5952227a36e32689e8b5fc9bf384  a0
801c5952227a36e32689e8b5fc9bf384  a1
801c5952227a36e32689e8b5fc9bf384  a2
199632c59a851d85b4a84beadd90c3c4  a3
801c5952227a36e32689e8b5fc9bf384  a4
801c5952227a36e32689e8b5fc9bf384  a5
801c5952227a36e32689e8b5fc9bf384  a6
801c5952227a36e32689e8b5fc9bf384  a7
801c5952227a36e32689e8b5fc9bf384  a8
801c5952227a36e32689e8b5fc9bf384  a9
52fbd38e5029a87b87db67e90ac4c294  b0
a9990d6eabf5a319071c4b71c3ea0731  b1
cb76902789d4b4bac7f834bb6fa1e577  b2
dc768c6a70f79bc35a27cdd0ff198db6  b3
52fbd38e5029a87b87db67e90ac4c294  b4
52fbd38e5029a87b87db67e90ac4c294  b5
52fbd38e5029a87b87db67e90ac4c294  b6
52fbd38e5029a87b87db67e90ac4c294  b7
52fbd38e5029a87b87db67e90ac4c294  b8
52fbd38e5029a87b87db67e90ac4c294  b9
0af60d7f24ac35de9f519197bc31cd22  c0
0af60d7f24ac35de9f519197bc31cd22  c1
0af60d7f24ac35de9f519197bc31cd22  c2
0af60d7f24ac35de9f519197bc31cd22  c3
0af60d7f24ac35de9f519197bc31cd22  c4
0af60d7f24ac35de9f519197bc31cd22  c5
0af60d7f24ac35de9f519197bc31cd22  c6
0af60d7f24ac35de9f519197bc31cd22  c7
0af60d7f24ac35de9f519197bc31cd22  c8
0af60d7f24ac35de9f519197bc31cd22  c9
shell@hammerhead:/sdcard/bbtest $ md5sum /data/app/com.adobe.reader-1/base.apk
0af60d7f24ac35de9f519197bc31cd22  /data/app/com.adobe.reader-1/base.apk
```

**Comment by d4rken** [comment]
Example files, somehow github says you can upload .zip, but you actually can't...

https://drive.google.com/file/d/0BwoXRNB2W15rZ1lxUDNmUE5SWVE/view?usp=sharing

**Comment by d4rken** [comment]
Reference on busybox mailing list:
http://lists.busybox.net/pipermail/busybox/2016-August/084519.html

**Comment by NinjaBoyLao** [comment]
This is definitely higher priority, i agree. i'm in an entire other state at the moment, on a quick little family vacation. still gonna put it up when i can get time

**Comment by d4rken** [comment]
Fix for this is basically done, I used this as a good excuse to make SD Maids binary handling more adaptive. It now can use both busybox and toybox, but by default ship with toybox.
It fixes this issue, binaries are smaller and looking at toyboxes code it's lean and mean :grin:.

Changing binaries isn't really a fix, but I didn't get anywhere on the busybox mailing list or with the busybox code. While switching binaries is kinda a bad workaround, it lead to much better code in SD Maid.
Previously busybox was pretty hardcoded, now it's all adaptive, so in the future we will have more options to tackle this kind of issues.
