### ISSUE TITLE
In-App-Purchase is unreliable, Google Play Service disconnects.

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#4674]
```kotlin
eu.thedarken.sdm.main.core.upgrades.iap.BillingClientException: Service connection is disconnected.
        at eu.thedarken.sdm.main.core.upgrades.iap.IAPRepo$startIAPFlow$1$1$1.onSkuDetailsResponse(IAPRepo.kt:190)
        at com.android.billingclient.api.BillingClientImpl.querySkuDetailsAsync(BillingClientImpl:259)
        at eu.thedarken.sdm.main.core.upgrades.iap.IAPRepo$startIAPFlow$1$1.subscribe(IAPRepo.kt:178)
        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
        at io.reactivex.internal.operators.observable.ObservableElementAtSingle$ElementAtObserver.onNext(ObservableElementAtSingle.java:89)
        at com.jakewharton.rx.ReplayingShare$LastSeenObserver.onSubscribe(ReplayingShare.java:131)
        at io.reactivex.internal.operators.observable.ObservableRefCount$RefCountObserver.onSubscribe(ObservableRefCount.java:266)
        at io.reactivex.internal.operators.observable.ObservablePublishAlt.subscribeActual(ObservablePublishAlt.java:101)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableRefCount.subscribeActual(ObservableRefCount.java:84)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at com.jakewharton.rx.ReplayingShare$LastSeenObservable.subscribeActual(ReplayingShare.java:113)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableElementAtSingle.subscribeActual(ObservableElementAtSingle.java:37)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleDoOnError.subscribeActual(SingleDoOnError.java:35)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:14935)
        at io.reactivex.Flowable.subscribe(Flowable.java:14882)
        at io.reactivex.internal.operators.flowable.FlowableRepeatWhen$WhenReceiver.onNext(FlowableRepeatWhen.java:100)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap:282)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:668)
        at io.reactivex.internal.operators.flowable.FlowableTimer$TimerSubscriber.run(FlowableTimer.java:76)
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

```kotlin
eu.thedarken.sdm.main.core.upgrades.iap.BillingClientException: Service connection is disconnected.
        at eu.thedarken.sdm.main.core.upgrades.iap.IAPRepo$startIAPFlow$1$1$1.onSkuDetailsResponse(IAPRepo.kt:190)
        at com.android.billingclient.api.BillingClientImpl.querySkuDetailsAsync(BillingClientImpl:259)
        at eu.thedarken.sdm.main.core.upgrades.iap.IAPRepo$startIAPFlow$1$1.subscribe(IAPRepo.kt:178)
        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
        at io.reactivex.internal.operators.observable.ObservableElementAtSingle$ElementAtObserver.onNext(ObservableElementAtSingle.java:89)
        at com.jakewharton.rx.ReplayingShare$LastSeenObserver.onSubscribe(ReplayingShare.java:131)
        at io.reactivex.internal.operators.observable.ObservableRefCount$RefCountObserver.onSubscribe(ObservableRefCount.java:266)
        at io.reactivex.internal.operators.observable.ObservablePublishAlt.subscribeActual(ObservablePublishAlt.java:101)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableRefCount.subscribeActual(ObservableRefCount.java:84)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at com.jakewharton.rx.ReplayingShare$LastSeenObservable.subscribeActual(ReplayingShare.java:113)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableElementAtSingle.subscribeActual(ObservableElementAtSingle.java:37)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleDoOnError.subscribeActual(SingleDoOnError.java:35)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:14935)
        at io.reactivex.Flowable.subscribe(Flowable.java:14882)
        at io.reactivex.internal.operators.flowable.FlowableRepeatWhen$WhenReceiver.onNext(FlowableRepeatWhen.java:100)
        at io.reactivex.internal.operators.flowable.FlowableRetryWhen.subscribeActual(FlowableRetryWhen.java:62)
        at io.reactivex.Flowable.subscribe(Flowable.java:14935)
        at io.reactivex.internal.operators.flowable.FlowableSingleSingle.subscribeActual(FlowableSingleSingle.java:39)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleResumeNext.subscribeActual(SingleResumeNext.java:39)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by d4rken** [comment]
Hm seems to be various issues?

```kotlin
1614733777542 W/UpgradeControl:IAPRepo: billingClient.onError()
BillingClientException(code=3, message=Google Play In-app Billing API version is less than 3)
	at e.a.a.a.a.a.a.a$i$b.a(IAPRepo.kt:9)
	at f0.b.a.a.q.run(com.android.billingclient:billing@@3.0.0:8)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7840)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:985)
```

```kotlin
D/UpgradeControl:IAPRepo: querySkuDetailsAsync(sku=UPGRADE_SDMAID_PRO): billingResult(responseCode=2, debugMessage=An internal error occurred.), skuDetailsList=[]
```

```kotlin
1614749466782 W/UpgradeControl:IAPRepo: billingClient.onError()
BillingClientException(code=3, message=Billing service unavailable on device.)
	at e.a.a.a.a.a.a.a$i$b.a(IAPRepo.kt:9)
	at e.a.a.a.a.a.a.a$i.a(IAPRepo.kt:49)
	at io.reactivex.internal.operators.observable.e.J(ObservableCreate.java:3)
	at io.reactivex.p.f(Observable.java:3)
	at io.reactivex.internal.operators.observable.w0$b.run(ObservableSubscribeOn.java:1)
	at io.reactivex.v$a.run(Scheduler.java:2)
	at io.reactivex.internal.schedulers.l.run(ScheduledRunnable.java:2)
	at io.reactivex.internal.schedulers.l.call(ScheduledRunnable.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by d4rken** [comment]
While not a guaranteed fix, I overhauled the IAP related code and included better retry behavior too.
