### ISSUE TITLE
Crash during StorageManager initialization

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#475]
```
Process: eu.thedarken.sdm
Flags: 0x98be44
Package: eu.thedarken.sdm v40300 (4.3.0)
Build: samsung/serranoltexx/serranolte:4.4.2/KOT49H/I9195XXUCOB1:user/release-keys

java.lang.NullPointerException
	at eu.thedarken.sdm.tools.storage.g.a(StorageHelper.java:29)
	at eu.thedarken.sdm.tools.storage.a.k.a(PrivateDataModule.java:41)
	at eu.thedarken.sdm.tools.storage.e.a(StorageFactory.java:114)
	at eu.thedarken.sdm.tools.storage.h.d(StorageManager.java:69)
	at eu.thedarken.sdm.tools.storage.h.<init>(StorageManager.java:40)
	at eu.thedarken.sdm.o.g(SDMContext.java:156)
	at eu.thedarken.sdm.o.a(SDMContext.java:187)
	at eu.thedarken.sdm.c$1.run(BaseConditions.java:6169)
	at eu.thedarken.sdm.u$1.run(WorkerOverlord.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at eu.thedarken.sdm.r$1.run(SDMThreadFactory.java:57)
	at java.lang.Thread.run(Thread.java:841)

```

Device is rooted and has an external sdcard.

SuperSU 2.78.

**Comment by d4rken** [comment]
Should crash SD Maid when starting any action and the StorageManager initializes.

**Comment by d4rken** [comment]
Fixed.
