### ISSUE TITLE
Crash when using back button up navigation

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#476]
Doesn't seem to be device specific.

```
java.lang.NullPointerException: Attempt to read from field 'eu.thedarken.sdm.biggest.Item eu.thedarken.sdm.biggest.Item.d' on a null object reference
        at eu.thedarken.sdm.biggest.BiggestFragment.a(BiggestFragment.java:30084)
        at eu.thedarken.sdm.SDMMainActivity.onKeyUp(SDMMainActivity.java:299)
        at eu.thedarken.sdm.SDMMainActivity$3.onKey(SDMMainActivity.java:208)
        at android.view.View.dispatchKeyEvent(View.java:8414)
```

Normal storage setup

```
DATA

/data | -1 | [PRIMARY] | null

OEM

/oem | -1 | [] | null

PUBLIC_DATA1

/storage/emulated/0/Android/data | 0 | [EMULATED, PRIMARY] | null

PUBLIC_DATA2

/storage/sdcard1/Android/data | -1 | [SECONDARY] | null

PUBLIC_MEDIA1

/storage/sdcard1/Android/media | -1 | [SECONDARY] | null

PUBLIC_MEDIA2

/storage/emulated/0/Android/media | 0 | [EMULATED, PRIMARY] | null

PUBLIC_OBB1

/storage/sdcard1/Android/obb | -1 | [SECONDARY] | null

PUBLIC_OBB2

/storage/emulated/0/Android/obb | 0 | [EMULATED, PRIMARY] | null

SDCARD1

/storage/sdcard1 | -1 | [SECONDARY] | content://com.android.externalstorage.documents/tree/1634-3809%3A

SDCARD2

/storage/emulated/0 | 0 | [EMULATED, PRIMARY] | null

SYSTEM

/system | -1 | [] | null

SYSTEM_APP

/system/app | -1 | [] | null

SYSTEM_PRIV_APP

/system/priv-app | -1 | [] | null

VENDOR

/vendor | -1 | [] | null
```

**Comment by d4rken** [comment]
"Current item" was not initiazied, checking that when pressing the backbutton (to see if we are at the root item)... npe.
