### ISSUE TITLE
Crash on updating storage analyzer progress

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#477]
```
java.lang.ArithmeticException: divide by zero
        at eu.thedarken.sdm.biggest.BiggestWorker$2.onPublish(BiggestWorker.java:121)
        at eu.thedarken.sdm.ui.ProgressUpdater.run(ProgressUpdater.java:32)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by d4rken** [comment]
Tool was too quick. Time passed = 0...
