### ISSUE TITLE
Crash when viewing `Android/data` on Android 11 via Explorer

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#4899]
> F: VERSIONNAME: 5.1.4, VERSIONCODE: 50104
> Fingerprint: samsung/p3quew/p3q:11/RP1A.200720.012/G998U1UEU3AUDD:user/release-keys

Seems like an edge case in the new SAF based read support.

```kotlin
1622575123472  W/null: Failed to fstat SAFPath: SAFFile(path=/storage/emulated/0/Android/data/com.android.systemui)
java.io.FileNotFoundException: open failed: EACCES (Permission denied)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1993)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1808)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1641)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1588)
	at e.a.a.b.j1.k0.g.b.d(SAFFile.kt:3)
	at e.a.a.b.j1.k0.g.b$d.a(SAFFile.kt:2)
	at j0.e.getValue(LazyJVM.kt:6)
	at e.a.a.b.j1.k0.g.b.n(SAFFile.kt:1)
	at e.a.a.f.b.d.n(ExplorerObject.java:1)
	at eu.thedarken.sdm.explorer.ui.ExplorerAdapter$ExplorerViewHolder.F(ExplorerAdapter.kt:25)
	at eu.thedarken.sdm.explorer.ui.ExplorerAdapter.q(ExplorerAdapter.kt:19)
	at e.a.a.e.c1.n.j.k(ModularRecyclerViewAdapter.java:2)
	at androidx.recyclerview.widget.RecyclerView$t.j(RecyclerView.java:168)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.v1(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.u0(LinearLayoutManager.java:126)
	at androidx.recyclerview.widget.RecyclerView.u(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView.s(RecyclerView.java:9)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:10)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at f0.f.a.b.n.d.layoutChild(HeaderScrollingViewBehavior.java:22)
	at f0.f.a.b.n.e.onLayoutChild(ViewOffsetBehavior.java:1)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:7)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:10)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1225)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4260)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3695)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:744)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by Zetotez** [comment]
> > F: VERSIONNAME: 5.1.4, VERSIONCODE: 50104
> > Fingerprint: samsung/p3quew/p3q:11/RP1A.200720.012/G998U1UEU3AUDD:user/release-keys
> 
> Seems like an edge case in the new SAF based read support.
> 
> ```kotlin
> 1622575123472  W/null: Failed to fstat SAFPath: SAFFile(path=/storage/emulated/0/Android/data/com.android.systemui)
> java.io.FileNotFoundException: open failed: EACCES (Permission denied)
> 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
> 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
> 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1993)
> 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1808)
> 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1641)
> 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1588)
> 	at e.a.a.b.j1.k0.g.b.d(SAFFile.kt:3)
> 	at e.a.a.b.j1.k0.g.b$d.a(SAFFile.kt:2)
> 	at j0.e.getValue(LazyJVM.kt:6)
> 	at e.a.a.b.j1.k0.g.b.n(SAFFile.kt:1)
> 	at e.a.a.f.b.d.n(ExplorerObject.java:1)
> 	at eu.thedarken.sdm.explorer.ui.ExplorerAdapter$ExplorerViewHolder.F(ExplorerAdapter.kt:25)
> 	at eu.thedarken.sdm.explorer.ui.ExplorerAdapter.q(ExplorerAdapter.kt:19)
> 	at e.a.a.e.c1.n.j.k(ModularRecyclerViewAdapter.java:2)
> 	at androidx.recyclerview.widget.RecyclerView$t.j(RecyclerView.java:168)
> 	at androidx.recyclerview.widget.LinearLayoutManager$c.c(LinearLayoutManager.java:9)
> 	at androidx.recyclerview.widget.LinearLayoutManager.v1(LinearLayoutManager.java:1)
> 	at androidx.recyclerview.widget.LinearLayoutManager.g1(LinearLayoutManager.java:12)
> 	at androidx.recyclerview.widget.LinearLayoutManager.u0(LinearLayoutManager.java:126)
> 	at androidx.recyclerview.widget.RecyclerView.u(RecyclerView.java:8)
> 	at androidx.recyclerview.widget.RecyclerView.s(RecyclerView.java:9)
> 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
> 	at android.view.View.layout(View.java:24475)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7383)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
> 	at android.view.View.layout(View.java:24475)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7383)
> 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:10)
> 	at android.view.View.layout(View.java:24475)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7383)
> 	at f0.f.a.b.n.d.layoutChild(HeaderScrollingViewBehavior.java:22)
> 	at f0.f.a.b.n.e.onLayoutChild(ViewOffsetBehavior.java:1)
> 	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1)
> 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:7)
> 	at android.view.View.layout(View.java:24475)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7383)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
> 	at android.view.View.layout(View.java:24475)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7383)
> 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:10)
> 	at android.view.View.layout(View.java:24475)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7383)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
> 	at android.view.View.layout(View.java:24475)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7383)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
> 	at android.view.View.layout(View.java:24475)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7383)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
> 	at android.view.View.layout(View.java:24475)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7383)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
> 	at android.view.View.layout(View.java:24475)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7383)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
> 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1225)
> 	at android.view.View.layout(View.java:24475)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7383)
> 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4260)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3695)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
> 	at android.view.Choreographer.doFrame(Choreographer.java:744)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loop(Looper.java:246)
> 	at android.app.ActivityThread.main(ActivityThread.java:8512)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
> ```
1622575123472  W/null: Failed to fstat SAFPath: SAFFile(path=/storage/emulated/0/Android/data/com.android.systemui)
java.io.FileNotFoundException: open failed: EACCES (Permission denied)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1993)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1808)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1641)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1588)
	at e.a.a.b.j1.k0.g.b.d(SAFFile.kt:3)
	at e.a.a.b.j1.k0.g.b$d.a(SAFFile.kt:2)
	at j0.e.getValue(LazyJVM.kt:6)
	at e.a.a.b.j1.k0.g.b.n(SAFFile.kt:1)
	at e.a.a.f.b.d.n(ExplorerObject.java:1)
	at eu.thedarken.sdm.explorer.ui.ExplorerAdapter$ExplorerViewHolder.F(ExplorerAdapter.kt:25)
	at eu.thedarken.sdm.explorer.ui.ExplorerAdapter.q(ExplorerAdapter.kt:19)
	at e.a.a.e.c1.n.j.k(ModularRecyclerViewAdapter.java:2)
	at androidx.recyclerview.widget.RecyclerView$t.j(RecyclerView.java:168)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.v1(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.u0(LinearLayoutManager.java:126)
	at androidx.recyclerview.widget.RecyclerView.u(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView.s(RecyclerView.java:9)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:10)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at f0.f.a.b.n.d.layoutChild(HeaderScrollingViewBehavior.java:22)
	at f0.f.a.b.n.e.onLayoutChild(ViewOffsetBehavior.java:1)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:7)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:10)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1225)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4260)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3695)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:744)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
