### ISSUE TITLE
Slow AppCleaner deletion of many small files via SAF

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#5098]
When the AppCleaner is evaluating and deleting many small files, it takes quite a look time per individual file.
It looks like some optimisations/checks are failing due to the files being accessed/referenced via SAF.

```java
1630780006676  D/SmartIO: Processing SmartDeleteTask(...)
1630780006676  D/a: WorkerStatus: WorkerStatus(isWorking=true, primary='TikTok Lite', secondary='/storage/emulated/0/Android/data/com.zhiliaoapp.musically.go/cache/picture/fresco_cache/v2.ols100.1/94/ya3FlcrR0In8yh5Y1PIU-usL9TU.cnt', progress=[5/98], isCancelable=true, progressType=DETERMINATE, isNewWorker=false)
1630780006677  V/SmartIO: determineWriteAccess([SAFFile(path=/storage/emulated/0/Android/data/com.zhiliaoapp.musically.go/cache/picture/fresco_cache/v2.ols100.1/94/ya3FlcrR0In8yh5Y1PIU-usL9TU.cnt)]):SAF
1630780006677  V/StorageVolumeMapper: getUri(): /storage/emulated/0/Android/data/com.zhiliaoapp.musically.go/cache/picture/fresco_cache/v2.ols100.1/94/ya3FlcrR0In8yh5Y1PIU-usL9TU.cnt -> content://com.android.externalstorage.documents/tree/primary%3A/document/primary%3AAndroid%2Fdata%2Fcom.zhiliaoapp.musically.go%2Fcache%2Fpicture%2Ffresco_cache%2Fv2.ols100.1%2F94%2Fya3FlcrR0In8yh5Y1PIU-usL9TU.cnt
1630780006683  V/null: SAF reading : PathPair(doc=content://com.android.externalstorage.documents/tree/primary%3A/document/primary%3AAndroid%2Fdata%2Fcom.zhiliaoapp.musically.go%2Fcache%2Fpicture%2Ffresco_cache%2Fv2.ols100.1%2F94%2Fya3FlcrR0In8yh5Y1PIU-usL9TU.cnt, path=/storage/emulated/0/Android/data/com.zhiliaoapp.musically.go/cache/picture/fresco_cache/v2.ols100.1/94/ya3FlcrR0In8yh5Y1PIU-usL9TU.cnt)
1630780006688  E/null: Failed query on content://com.android.externalstorage.documents/tree/primary%3A/document/primary%3AAndroid%2Fdata%2Fcom.zhiliaoapp.musically.go%2Fcache%2Fpicture%2Ffresco_cache%2Fv2.ols100.1%2F94%2Fya3FlcrR0In8yh5Y1PIU-usL9TU.cnt
java.lang.IllegalArgumentException: Failed to determine if primary:Android/data/com.zhiliaoapp.musically.go/cache/picture/fresco_cache/v2.ols100.1/94/ya3FlcrR0In8yh5Y1PIU-usL9TU.cnt is child of primary:: java.io.FileNotFoundException: Missing file for primary:Android/data/com.zhiliaoapp.musically.go/cache/picture/fresco_cache/v2.ols100.1/94/ya3FlcrR0In8yh5Y1PIU-usL9TU.cnt at /storage/emulated/0/Android/data/com.zhiliaoapp.musically.go/cache/picture/fresco_cache/v2.ols100.1/94/ya3FlcrR0In8yh5Y1PIU-usL9TU.cnt
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
	at android.content.ContentResolver.query(ContentResolver.java:1197)
	at android.content.ContentResolver.query(ContentResolver.java:1128)
	at android.content.ContentResolver.query(ContentResolver.java:1084)
	at d0.f.a.b.a.j0(Unknown Source:8)
	at c.a.a.b.k1.j0.f.b.d(SAFDeleteTool.kt:12)
	at c.a.a.b.k1.j0.f.b.c(SAFDeleteTool.kt:11)
	at c.a.a.b.k1.j0.a.c(Unknown Source:7)
	at c.a.a.b.k1.z.c(SmartIO.java:21)
	at c.a.a.d.a.b.a.d.g(DeleteModule.kt:57)
	at c.a.a.d.a.a.I(AppCleanerWorker.kt:4)
	at c.a.a.a.a.l0.l$b.run(WorkerHub.java:6)
	at c.a.a.a.a.s.run(lambda:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at c.a.a.a.a.o.run(lambda:6)
	at java.lang.Thread.run(Thread.java:923)

1630780006694  V/SAFIO:Delete: Deletion successful: [/storage/emulated/0/Android/data/com.zhiliaoapp.musically.go/cache/picture/fresco_cache/v2.ols100.1/94/ya3FlcrR0In8yh5Y1PIU-usL9TU.cnt] AKA [/tree/primary:/document/primary:Android/data/com.zhiliaoapp.musically.go/cache/picture/fresco_cache/v2.ols100.1/94/ya3FlcrR0In8yh5Y1PIU-usL9TU.cnt]
1630780006694  D/SmartIO: Delete result: SAFDeleteResult(state=OK, affectedsize=0, deletedFiles=1, errorFiles=0)
````
edit:
:point_up: this actually shows a case where the file was already deleted, or the ROMs SAF provider is not working correctly.
If SD Maid doesn't get `true` when calling `delete()`, we check if the file still exists, and then assume deletion was successful.
In this case though I think the file was already cleared from cache before SD Maid could attempt to delete it.

**Comment by d4rken** [comment]
Unfortunately there is nothing really wrong here AFAICT.
The issues comes when there are many files in a single top level-directory.
e.g.
`<pkg>/topleveldir/<many files>`

SD Maid then can't (won't) delete `topleveldir`, all files in that dir that should be deleted, will have to be deleted 1by1, which is just slower using SAF.

Telegram seems to match that structure a lot:

```java
1630780148540  D/SmartIO: Processing SmartDeleteTask(...)
1630780148541  V/SmartIO: determineWriteAccess([SAFFile(path=/storage/emulated/0/Android/data/org.telegram.messenger/cache/-5251344341614573882_109.jpg)]):SAF
1630780148541  D/a: WorkerStatus: WorkerStatus(isWorking=true, primary='Telegram', secondary='/storage/emulated/0/Android/data/org.telegram.messenger/cache/-5251344341614573882_109.jpg', progress=[6/98], isCancelable=true, progressType=DETERMINATE, isNewWorker=false)
1630780148541  V/StorageVolumeMapper: getUri(): /storage/emulated/0/Android/data/org.telegram.messenger/cache/-5251344341614573882_109.jpg -> content://com.android.externalstorage.documents/tree/primary%3A/document/primary%3AAndroid%2Fdata%2Forg.telegram.messenger%2Fcache%2F-5251344341614573882_109.jpg
1630780148542  D/OneClickFragment: updateAppCleaner: WorkerStatus(isWorking=true, primary='Telegram', secondary='/storage/emulated/0/Android/data/org.telegram.messenger/cache/-5251344341614573882_109.jpg', progress=[6/98], isCancelable=true, progressType=DETERMINATE, isNewWorker=false) CANCEL
1630780148592  V/SAFIO:Delete: Deletion successful: [/storage/emulated/0/Android/data/org.telegram.messenger/cache/-5251344341614573882_109.jpg] AKA [/tree/primary:/document/primary:Android/data/org.telegram.messenger/cache/-5251344341614573882_109.jpg]
1630780148592  D/SmartIO: Delete result: SAFDeleteResult(state=OK, affectedsize=3649, deletedFiles=1, errorFiles=0)
```

**Comment by d4rken** [comment]
I don't see a way to speed this up :frowning:

**Comment by Nemris** [comment]
@d4rken Wouldn't it be possible to act directly on `/data/media/0` instead of using SAF on rooted devices? If the experience from my own tinkering days holds true, that should let you work directly on the actual storage, also bypassing the FUSE layer.

**Comment by d4rken** [comment]
Hm last I checked if rooted, SD Maid would use that instead of SAF.

Making SD Maid work with `/data/media/0` is a lot more work, possibly huge headache, not sure I'm up for that atm :frowning_face:.
