### ISSUE TITLE
Bug: Accessibility service is always on but is always malfunctioning 

### ISSUE THREAD

**Issue by Ronantm** [d4rken/sdmaid-public#5129]
### What happened?
The app can't auto clear the caches during app cleaner 

### What did you expect to happen?
I checked my phone's acc settings in menu and it says it's turned on but malfunctipnkng. I restart phone and turn the setting on and off. Keeps failing.  

### How can I reproduce the issue?
Run the app cleaner with all extras included except telegram 

### Comments
It will sometimes work but often less than it will 
### SD Maid
Version: `5.2.0 (50200)`
Pro: `isPro=true || isComplete=true (unl=false, iap=true, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `Xiaomi/apollopro_global/apollo:11/RKQ1.200826.002/V12.5.4.0.RJDMIXM:user/release-keys`

**Comment by d4rken** [comment]
It does not turn on after a reboot? and turning the service off/on ?
Can you record a debuglog of that?
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

**Comment by d4rken** [comment]
You can't attach by email, you have to upload the log on Github.

> Yeah tried both ways often and it doesn't fix the issue.

So it never works? Or only sometimes?

**Comment by Ronantm** [comment]
Only sometimes... Most of the time it doesn't 

Where's the attach button here lol sorry

**Comment by Ronantm** [comment]
[sdmaid_logfile_1633520472251.txt.zip](https://github.com/d4rken/sdmaid-public/files/7293553/sdmaid_logfile_1633520472251.txt.zip)

**Comment by d4rken** [comment]
It seems to launch okay in the beginning

```java
1633520551184  D/ACC:Service: onCreate(application=eu.thedarken.sdm.App@c6fb858)
1633520551184  D/ACC:Service: Injecting via service.application.
1633520551216  D/ACC:Service: onServiceConnected
```

then a bit later when it should be used it fails to show the progress window

```java
1633520559427  D/ACC:Service: Adding new controlview: eu.thedarken.sdm.accessibility.ui.ACControlView{86742dd V.E...... ......I. 0,0-0,0}
1633520559431  D/ACC:Service:Processor: Processing QueuedTask(task=r5.c@309ba20, emitter=a{null})
1633520559431  I/ACC:Service:Processor: QueuedTask(task=r5.c@309ba20, emitter=a{null}) was canceled before execution.
1633520559433  D/d: WorkerStatus: WorkerStatus(isWorking=true, primary='Working: Statistics', secondary='null', progress=[155/155], isCancelable=true, progressType=DETERMINATE, isNewWorker=false)
1633520559433  D/d: WorkerStatus: WorkerStatus(isWorking=true, primary='Working: Statistics', secondary='null', progress=[155/155], isCancelable=true, progressType=DETERMINATE, isNewWorker=false)
1633520559434  D/ACC:Service: Removing controlview: eu.thedarken.sdm.accessibility.ui.ACControlView{86742dd V.E...... ......I. 0,0-0,0}
1633520559434  W/ACC:Service: Failed to remove controlview, possibly failed to add it in the first place: eu.thedarken.sdm.accessibility.ui.ACControlView{86742dd V.E...... ......I. 0,0-0,0}
java.lang.IllegalArgumentException: View=eu.thedarken.sdm.accessibility.ui.ACControlView{86742dd V.E...... ......I. 0,0-0,0} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:572)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:476)
	at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:139)
	at k5.m.run(Unknown Source:33)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

1633520559441  E/WorkerHub:Processor:d: Exception during task processing!
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1140)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:111)
	at k5.j.run(Unknown Source:19)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

But that might actually be correct behavior as shortly before failing to remove the UI elements, there is

```
1633520559431  I/ACC:Service:Processor: QueuedTask(task=r5.c@309ba20, emitter=a{null}) was canceled before execution.
```

So the task was canceled.

I'd say the log looks as expected :thinking: 

Can you show a screen video, to show your perspective?

**Comment by Ronantm** [comment]
I don't push anything to cancel the task though at the end

**Comment by Ronantm** [comment]
https://user-images.githubusercontent.com/82264604/136204822-d5a34ba9-cac0-4c7f-b986-b0b1706a9234.mp4

**Comment by Ronantm** [comment]
https://user-images.githubusercontent.com/82264604/136205675-ddedb43e-41f1-4b73-8d06-04aeef8abb91.mp4

**Comment by Ronantm** [comment]
Sorry I had trouble uploading the screen record but I think that should be okay now. See at end of video it won't allow it.. I don't push anything to make that happen

**Comment by Ronantm** [comment]
https://user-images.githubusercontent.com/82264604/136208109-5906a5b6-aa0c-4a0b-84f9-49fc4cb1854d.mp4

**Comment by Ronantm** [comment]
![Screenshot_2021-10-07-00-04-06-466_eu thedarken sdm](https://user-images.githubusercontent.com/82264604/136208335-f74e7fb6-0489-4be3-9c9a-64026cce3b16.jpg)

**Comment by Ronantm** [comment]
![Screenshot_2021-10-07-00-04-06-466_eu thedarken sdm](https://user-images.githubusercontent.com/82264604/136208633-ca7e5261-d388-4d3c-886e-c2c9465cebfd.jpg)
![Screenshot_2021-10-07-00-03-57-385_com android settings](https://user-images.githubusercontent.com/82264604/136208648-a2134caf-4bbc-436d-b407-9287b60cc50c.jpg)
![Screenshot_2021-10-07-00-03-52-833_com android settings](https://user-images.githubusercontent.com/82264604/136208664-83b3a745-8b55-4f7f-806b-f03faaf47983.jpg)
![Screenshot_2021-10-07-00-03-48-127_eu thedarken sdm](https://user-images.githubusercontent.com/82264604/136208674-42392c02-ea95-4266-902c-60acd9a0cda6.jpg)
![Screenshot_2021-10-07-00-03-48-127_eu thedarken sdm](https://user-images.githubusercontent.com/82264604/136208692-f05add14-a1a4-4a84-b312-6b0f13da0411.jpg)

**Comment by d4rken** [comment]
Seems the service just crashes.
Log or crash tracking doesn't show why though :frowning: 

Could you take a device-wide bugreport?
Shortly after reproducing the issue (minutes later is okay, just not hours, otherwise it's not visible in the log).
See instructions here:
https://developer.android.com/studio/debug/bug-report

Do not upload it here as that log could contain sensitive information.
Upload it somewhere and share the link via email with me.

**Comment by d4rken** [comment]
There is also a new beta available now, v5.2.1:
https://sdmaid.darken.eu/download/beta/
https://sdmaid.darken.eu/beta

Also try that :wink:

**Comment by d4rken** [comment]
Awesome :muscle: 
This is a solo project btw, just me here :wink:
