### ISSUE TITLE
Crash if the page that was last active is hidden through settings

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#525]
https://www.youtube.com/watch?v=spEsGnM0RCI

SD Maid likely crashes when trying to restore a previous page that is no longer loaded by the navigation fragment.

**Comment by d4rken** [comment]
Actually I was wrong, it's the support library from Google causing it.

http://stackoverflow.com/questions/39536519/java-lang-illegalargumentexception-rect-should-intersect-with-childs-bounds
https://code.google.com/p/android/issues/detail?id=222597

```
09-23 10:58:44.036 D/AndroidRuntime(15940): Shutting down VM
09-23 10:58:44.063 E/AndroidRuntime(15940): FATAL EXCEPTION: main
09-23 10:58:44.063 E/AndroidRuntime(15940): Process: eu.thedarken.sdm, PID: 15940
09-23 10:58:44.063 E/AndroidRuntime(15940): Theme: themes:{}
09-23 10:58:44.063 E/AndroidRuntime(15940): java.lang.IllegalArgumentException: Rect should intersect with child's bounds.
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at android.support.design.widget.CoordinatorLayout.a(SourceFile:15319)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at android.support.design.widget.CoordinatorLayout$e.onPreDraw(SourceFile:1805)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2063)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at android.view.Choreographer.doFrame(Choreographer.java:606)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at android.os.Handler.handleCallback(Handler.java:739)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at android.os.Looper.loop(Looper.java:148)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at java.lang.reflect.Method.invoke(Native Method)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-23 10:58:44.063 E/AndroidRuntime(15940): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
09-23 10:58:44.065 W/ActivityManager(  734):   Force finishing activity eu.thedarken.sdm/.SDMMainActivity
```

**Comment by Alexey71** [comment]
In version 3.3.2 there is no crash

**Comment by d4rken** [comment]
The support library was updated in v4.3.3 which fixed a few other bugs, but introduced this one 😦 .
We'll have to wait for Google to update the support library.

**Comment by prasanthrn2k** [comment]
I am waiting

**Comment by d4rken** [comment]
I reviewed previous crashes in v4.3.2 and this crash seems common than any other issue the upgrade may fix. Downgrading until Google fixes this.
