### ISSUE TITLE
Gracefully deal with items that were ommitted during scan due to invalid stats

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#668]
Example:

```
1483105410947 V/SDM:InteractiveShell: Output: 770:directory:28:26741:10124:9997:4096:512:8:18446744072363093454:`/storage/emulated/0/Android/data/com.miui.systemAdSolution'
1483105410947 V/SDM:InteractiveShell: Output: 770:directory:28:26742:10124:9997:4096:512:8:18446744072363093454:`/storage/emulated/0/Android/data/com.miui.systemAdSolution/files'
1483105410948 E/SDM:SDMBox:Stat:Factory: java.lang.NumberFormatException: Invalid long: "18446744072363093454"
	at java.lang.Long.invalidLong(Long.java:124)
	at java.lang.Long.parse(Long.java:366)
	at java.lang.Long.parseLong(Long.java:353)
	at java.lang.Long.parseLong(Long.java:321)
	at eu.thedarken.sdm.tools.binaries.a.a.t$a.a(StatApplet.java:251)
	at eu.thedarken.sdm.tools.binaries.a.a.t$a$a.a(StatApplet.java:166)
	at eu.thedarken.sdm.tools.io.shell.g$1.a(ShellReadTask.java:43)
	at eu.thedarken.sdm.tools.shell.a$1.a(Command.java:51)
	at eu.thedarken.sdm.tools.shell.a.c.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)

1483105410948 V/SDM:InteractiveShell: Output: 770:directory:28:26743:10124:9997:4096:512:8:1482764562:`/storage/emulated/0/Android/data/com.miui.systemAdSolution/files/miad'
1483105410948 V/SDM:InteractiveShell: Output: 770:directory:28:26744:10124:9997:4096:512:8:1482764563:`/storage/emulated/0/Android/data/com.miui.systemAdSolution/files/miad/files'
1483105410949 V/SDM:InteractiveShell: Output: 660:regular file:28:26745:10124:9997:1378:512:8:1483084518:`/storage/emulated/0/Android/data/com.miui.systemAdSolution/files/miad/files/splashconfig'
1483105410949 E/SDM:SDMBox:Stat:Factory: java.lang.NumberFormatException: Invalid long: "18446744072363093454"
	at java.lang.Long.invalidLong(Long.java:124)
	at java.lang.Long.parse(Long.java:366)
	at java.lang.Long.parseLong(Long.java:353)
	at java.lang.Long.parseLong(Long.java:321)
	at eu.thedarken.sdm.tools.binaries.a.a.t$a.a(StatApplet.java:251)
	at eu.thedarken.sdm.tools.binaries.a.a.t$a$a.a(StatApplet.java:166)
	at eu.thedarken.sdm.tools.io.shell.g$1.a(ShellReadTask.java:43)
	at eu.thedarken.sdm.tools.shell.a$1.a(Command.java:51)
	at eu.thedarken.sdm.tools.shell.a.c.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)

1483105410949 V/SDM:InteractiveShell: Output: 770:directory:28:28362:10124:9997:4096:512:8:1482860829:`/storage/emulated/0/Android/data/com.miui.systemAdSolution/files/miad/cache'
1483105410950 V/SDM:InteractiveShell: Output: 660:regular file:28:28363:10124:9997:6106:512:16:1483084518:`/storage/emulated/0/Android/data/com.miui.systemAdSolution/files/miad/cache/2476413951'
1483105410950 V/SDM:InteractiveShell: Output: 660:regular file:28:28364:10124:9997:5608:512:16:1483084518:`/storage/emulated/0/Android/data/com.miui.systemAdSolution/files/miad/cache/3414822307'
1483105410951 V/SDM:InteractiveShell: Output: 660:regular file:28:28365:10124:9997:54507:512:112:1483084518:`/storage/emulated/0/Android/data/com.miui.systemAdSolution/files/miad/cache/1952555180'
1483105410951 V/SDM:InteractiveShell: Output: 660:regular file:28:28366:10124:9997:16840:512:40:1483084518:`/storage/emulated/0/Android/data/com.miui.systemAdSolution/files/miad/cache/2908347380'
1483105410952 V/SDM:InteractiveShell: Output: 660:regular file:28:28367:10124:9997:62729:512:128:1483084518:`/storage/emulated/0/Android/data/com.miui.systemAdSolution/files/miad/cache/3961831611'
1483105410952 V/SDM:InteractiveShell: Output: 660:regular file:28:28368:10124:9997:5748:512:16:1483084518:`/storage/emulated/0/Android/data/com.miui.systemAdSolution/files/miad/cache/2054502533'
1483105410953 V/SDM:InteractiveShell: Output: 660:regular file:28:28369:10124:9997:55109:512:112:1483084518:`/storage/emulated/0/Android/data/com.miui.systemAdSolution/files/miad/cache/1205473693'
1483105410953 V/SDM:InteractiveShell: Output: 660:regular file:28:28370:10124:9997:57557:512:120:1483084518:`/storage/emulated/0/Android/data/com.miui.systemAdSolution/files/miad/cache/386471344'
1483105410954 V/SDM:InteractiveShell: Output: 660:regular file:28:28371:10124:9997:120715:512:240:1483084528:`/storage/emulated/0/Android/data/com.miui.systemAdSolution/files/miad/cache/738043886'
```

The time value of "18446744072363093454" seconds since epoch, leads SD Maid to ignore the parent folder not but not the children whose stats are valid. When the file tree is then generated there is no parent to anchor the children into leading to an error.

![screenshot_2016-12-30-10-11-19-941_eu thedarken sdm](https://cloud.githubusercontent.com/assets/1439229/21569297/f36cce18-cebb-11e6-9e58-e60faaf1f748.png)

**Comment by d4rken** [comment]
http://lists.landley.net/pipermail/toybox-landley.net/2016-December/008787.html
