### ISSUE TITLE
Crash when trying to create clutter report

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#686]
Reproduced on v4.5.8.

When pressing "Suggest owners" in the clutter report screen, the app crashes.

```
java.lang.ClassCastException: android.support.v7.widget.ar$a cannot be cast to android.widget.LinearLayout$LayoutParams
	at android.support.v7.app.d.onCreate(AlertDialog.java:2655)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:373)
	at android.app.Dialog.show(Dialog.java:274)
	at eu.thedarken.sdm.tools.clutter.report.e.onClick(Unknown Source)
	at android.view.View.performClick(View.java:4781)
	at android.view.View$PerformClick.run(View.java:19874)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5333)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:735)

```

**Comment by d4rken** [comment]
Not present on v4.5.7, maybe related to the support library update? See #685

**Comment by d4rken** [comment]
https://code.google.com/p/android/issues/detail?id=231238
