### ISSUE TITLE
Crash on LG devices when using `killBackgroundProcesses`

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#748]
There seems to be a ROM bug on LG devices (e.g. LG-H830 [NRD90U], LG-H850[NRD90U], LG-H918[NRD90M]) running Android 7.0 where the system call `killBackgroundProcesses` can throw an NPE, probably a race condition.

Some ASUS devices on Android 5.0 (K00E, K00Z, K016) also seem to exhibit this.

Not sure about fixing this yet, isn't really SD Maids fault.

```
java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.android.server.am.ProcessRecord.processName' on a null object reference
        at android.os.Parcel.readException(Parcel.java:1689)
        at android.os.Parcel.readException(Parcel.java:1636)
        at android.app.ActivityManagerProxy.killBackgroundProcesses(ActivityManagerNative.java:5246)
        at android.app.ActivityManager.killBackgroundProcesses(ActivityManager.java:3132)
```

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.SparseArray.size()' on a null object reference
        at android.os.Parcel.readException(Parcel.java:1546)
        at android.os.Parcel.readException(Parcel.java:1493)
        at android.app.ActivityManagerProxy.killBackgroundProcesses(ActivityManagerNative.java:4176)
        at android.app.ActivityManager.killBackgroundProcesses(ActivityManager.java:2294)
```

**Comment by d4rken** [comment]
Alright let's throw LG users a bone here and catch this...

First thought this might be some custom ROM shenigans, but this looks like a legit ROM for those device.

LG 😦

**Comment by d4rken** [comment]
![lg](https://cloud.githubusercontent.com/assets/1439229/23022418/f5410ca8-f450-11e6-8290-f7abdb93acfc.PNG)
