### ISSUE TITLE
SDCard permission setup fails on Oppo Neo 7

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#750]
Device doesn't supply any information SD Maid can use to map so far.

The permission generates the URI: `uri=content://com.android.externalstorage.documents/tree/131073:` and we are trying to match `StorageVolumeX: StorageVolumeX(uuid=null, state=mounted, path=/storage/sdcard1, primary=false, emulated=false, owner=null, userlabel=null)`.
```
1487127024604 I/Debug: F: VERSIONNAME:4.5.9; VERSIONCODE:40509
1487127024612 I/Debug: P: VERSIONNAME:4.0.11; VERSIONCODE:40011
1487127024624 D/Debug: ro.build.id=LMY47I
1487127024625 D/Debug: ro.build.version.incremental=1484041933
1487127024625 D/Debug: ro.build.version.sdk=22
1487127024625 D/Debug: ro.build.version.codename=REL
1487127024626 D/Debug: ro.build.version.all_codenames=REL
1487127024626 D/Debug: ro.build.version.release=5.1
1487127024626 D/Debug: ro.build.version.security_patch=2016-12-05
1487127024627 D/Debug: ro.build.version.base_os=OPPO/A33w/A33w:5.1/LMY47I/1475371479:user/release-keys
1487127024628 D/Debug: ro.build.date=Tue Jan 10 17:53:30 CST 2017
1487127024628 D/Debug: ro.build.date.utc=1484042010
1487127024629 D/Debug: ro.build.type=user
1487127024629 D/Debug: ro.build.user=root
1487127024630 D/Debug: ro.build.host=WX-122-169
1487127024630 D/Debug: ro.build.tags=release-keys
1487127024630 D/Debug: ro.build.flavor=full_oppo6582_15093-user
1487127024631 D/Debug: ro.product.cpu.abi=armeabi-v7a
1487127024631 D/Debug: ro.product.cpu.abi2=armeabi
1487127024631 D/Debug: ro.product.cpu.abilist=armeabi-v7a,armeabi
1487127024632 D/Debug: ro.product.cpu.abilist32=armeabi-v7a,armeabi
1487127024633 D/Debug: ro.product.cpu.abilist64=
1487127024634 D/Debug: ro.product.manufacturer=OPPO
1487127024635 D/Debug: ro.product.locale.language=en
1487127024636 D/Debug: ro.product.locale.region=US
1487127024637 D/Debug: ro.build.description=full_oppo6582_15093-user 5.1 LMY47I 1484041933 release-keys
1487127024639 D/Debug: ro.build.characteristics=default
1487127024642 D/Debug: ro.build.date.Ymd=170110
1487127024642 D/Debug: ro.build.date.ymd=170110
1487127024643 D/Debug: ro.build.date.YmdHM=201701101753
1487127024643 D/Debug: ro.product.model=A33w
1487127024644 D/Debug: ro.product.brand=OPPO
1487127024644 D/Debug: ro.product.name=A33w
1487127024645 D/Debug: ro.product.device=A33w
1487127024645 D/Debug: ro.product.board=
1487127024646 D/Debug: ro.build.product=A33w
1487127024646 D/Debug: ro.build.soft.version=A.22
1487127024647 D/Debug: ro.build.soft.majorversion=
1487127024647 D/Debug: ro.build.ota.versionname=A33wEX_11_170110
1487127024648 D/Debug: ro.build.kernel.id=3.10.48-G201701101645
1487127024649 D/Debug: ro.build.fingerprint=OPPO/A33w/A33w:5.1/LMY47I/1482732905:user/release-keys
1487127024649 D/Debug: ro.build.version.ota=A33wEX_11.A.22_INT_022_201701101645
1487127024649 D/Debug: ro.build.display.id=A33wEX_11_170110
1487127024652 D/Debug: ro.build.display.full_id=A33wEX_11_A.22_170110
1487127024653 D/Debug: ro.build.version.opporom=V2.1.0i
```

```
1487127044273 V/Fragment:SAFSetupFragment(1377812): onActivityResult(requestCode=100, resultCode=-1, data=Intent { dat=content://com.android.externalstorage.documents/tree/131073: flg=0xc3 })
1487127044275 D/StorageVolumeMapper: Updating mappings.
1487127044281 D/StorageVolumeMapper: Trying to map: UriPermission {uri=content://com.android.externalstorage.documents/tree/131073%3A, modeFlags=3, persistedTime=1487127044274}
1487127044282 D/StorageVolumeRepository: Attempting getVolumeRoot(UriPermission {uri=content://com.android.externalstorage.documents/tree/131073%3A, modeFlags=3, persistedTime=1487127044274}) via getVolumeList().
1487127044285 D/StorageVolumeRepository: StorageVolumeX: StorageVolumeX(uuid=null, state=mounted, path=/storage/emulated/0, primary=true, emulated=true, owner=UserHandle{0}, userlabel=null)
1487127044287 D/StorageVolumeRepository: StorageVolumeX: StorageVolumeX(uuid=null, state=mounted, path=/storage/sdcard1, primary=false, emulated=false, owner=null, userlabel=null)
1487127044288 W/StorageVolumeRepository: Missing UUID for StorageVolumeX(uuid=null, state=mounted, path=/storage/sdcard1, primary=false, emulated=false, owner=null, userlabel=null)
1487127044288 D/StorageVolumeRepository: StorageVolumeX: StorageVolumeX(uuid=null, state=removed, path=/storage/usbotg, primary=false, emulated=false, owner=null, userlabel=null)
1487127044289 W/StorageVolumeRepository: Failed to build VolumeRoot via StorageVolume.
eu.thedarken.sdm.tools.storage.oswrapper.mapper.StorageAccessFrameworkException: No matching StorageVolume for: UriPermission {uri=content://com.android.externalstorage.documents/tree/131073%3A, modeFlags=3, persistedTime=1487127044274}
	at eu.thedarken.sdm.tools.storage.oswrapper.mapper.a.a(BaseRepository.java:53)
	at eu.thedarken.sdm.tools.storage.oswrapper.mapper.c.a(StorageVolumeMapper.java:107)
	at eu.thedarken.sdm.setup.SAFSetupFragment.a(SAFSetupFragment.java:221)
	at android.support.v4.app.p.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:6337)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3855)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3902)
	at android.app.ActivityThread.access$1300(ActivityThread.java:182)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:218)
	at android.app.ActivityThread.main(ActivityThread.java:5657)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)

1487127044291 E/StorageVolumeRepository: getVolumeRoot(UriPermission {uri=content://com.android.externalstorage.documents/tree/131073%3A, modeFlags=3, persistedTime=1487127044274}) via getVolumeList() failed.
1487127044292 E/StorageVolumeMapper: eu.thedarken.sdm.tools.exceptions.MissingVolumeRootException: No VolumeRoot for: /tree/131073:
	at eu.thedarken.sdm.tools.storage.oswrapper.mapper.c.a(StorageVolumeMapper.java:115)
	at eu.thedarken.sdm.setup.SAFSetupFragment.a(SAFSetupFragment.java:221)
	at android.support.v4.app.p.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:6337)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3855)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3902)
	at android.app.ActivityThread.access$1300(ActivityThread.java:182)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:218)
	at android.app.ActivityThread.main(ActivityThread.java:5657)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)

1487127044316 E/UriAccessFragment: Invalid uri permission for Storage(location=SDCARD, path=/storage/sdcard1, userHandle=-1, flags=[SECONDARY], safUri=null, mount=Mountpoint(path=/storage/sdcard1, blockDevice=/dev/fuse, fileSystemType=FUSE, options=[nodev, group_id=1023, relatime, rw, nosuid, default_permissions, allow_other, user_id=1023, noexec])), releasing: content://com.android.externalstorage.documents/tree/131073%3A
```

```
1487127030859 V/InteractiveShell: Input : $SDMBOX mount

1487127030859 V/InteractiveShell: Input : echo 4fb8255d-a167-4c7b-a88e-44ff90df5328 $?

1487127030860 V/InteractiveShell: Input : echo 4fb8255d-a167-4c7b-a88e-44ff90df5328 >&2

1487127030864 V/InteractiveShell: Output: rootfs on / type rootfs (ro,seclabel)
1487127030864 V/InteractiveShell: Output: tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,mode=755)
1487127030865 V/InteractiveShell: Output: devpts on /dev/pts type devpts (rw,seclabel,relatime,mode=600)
1487127030865 V/InteractiveShell: Output: none on /dev/cpuctl type cgroup (rw,relatime,cpu)
1487127030866 V/InteractiveShell: Output: adb on /dev/usb-ffs/adb type functionfs (rw,relatime)
1487127030866 V/InteractiveShell: Error : 4fb8255d-a167-4c7b-a88e-44ff90df5328
1487127030866 V/InteractiveShell: Output: proc on /proc type proc (rw,relatime)
1487127030866 V/InteractiveShell: Output: sysfs on /sys type sysfs (rw,seclabel,relatime)
1487127030867 V/InteractiveShell: Output: selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
1487127030867 V/InteractiveShell: Output: none on /sys/fs/cgroup type tmpfs (rw,seclabel,relatime,mode=750,gid=1000)
1487127030867 V/InteractiveShell: Output: debugfs on /sys/kernel/debug type debugfs (rw,seclabel,relatime)
1487127030868 V/InteractiveShell: Output: none on /acct type cgroup (rw,relatime,cpuacct)
1487127030868 V/InteractiveShell: Output: tmpfs on /mnt/asec type tmpfs (rw,seclabel,relatime,mode=755,gid=1000)
1487127030868 V/InteractiveShell: Output: tmpfs on /mnt/obb type tmpfs (rw,seclabel,relatime,mode=755,gid=1000)
1487127030868 V/InteractiveShell: Output: tmpfs on /storage/emulated type tmpfs (rw,seclabel,relatime,mode=755,uid=1023,gid=1023)
1487127030869 V/InteractiveShell: Output: tmpfs on /storage/emulated type tmpfs (rw,seclabel,nosuid,nodev,relatime,mode=751,gid=1028)
1487127030869 V/InteractiveShell: Output: /emmc@android on /system type ext4 (ro,seclabel,relatime,data=ordered)
1487127030869 V/InteractiveShell: Output: /emmc@usrdata on /data type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,noauto_da_alloc,data=ordered)
1487127030870 V/InteractiveShell: Output: /emmc@cache on /cache type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,noauto_da_alloc,data=ordered)
1487127030870 V/InteractiveShell: Output: /emmc@protect_f on /protect_f type ext4 (rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered)
1487127030870 V/InteractiveShell: Output: /emmc@protect_s on /protect_s type ext4 (rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered)
1487127030870 V/InteractiveShell: Output: /dev/block/loop0 on /mnt/cd-rom type iso9660 (ro,relatime)
1487127030871 V/InteractiveShell: Output: /dev/fuse on /mnt/shell/emulated type fuse (rw,nosuid,nodev,noexec,relatime,user_id=1023,group_id=1023,default_permissions,allow_other)
1487127030871 V/InteractiveShell: Output: /dev/block/vold/179:129 on /mnt/media_rw/sdcard1 type vfat (rw,dirsync,nosuid,nodev,noexec,relatime,uid=1023,gid=1023,fmask=0007,dmask=0007,allow_utime=0020,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro)
1487127030871 V/InteractiveShell: Output: /dev/fuse on /storage/sdcard1 type fuse (rw,nosuid,nodev,noexec,relatime,user_id=1023,group_id=1023,default_permissions,allow_other)
1487127030872 V/InteractiveShell: Output: /dev/fuse on /storage/emulated/0 type fuse (rw,nosuid,nodev,noexec,relatime,user_id=1023,group_id=1023,default_permissions,allow_other)
1487127030872 V/InteractiveShell: Output: /dev/fuse on /storage/emulated/legacy type fuse (rw,nosuid,nodev,noexec,relatime,user_id=1023,group_id=1023,default_permissions,allow_other)
1487127030872 V/InteractiveShell: Output: tmpfs on /mnt/shell/emulated type tmpfs (rw,seclabel,nosuid,nodev,relatime,mode=700)
1487127030872 V/InteractiveShell: Output: 4fb8255d-a167-4c7b-a88e-44ff90df5328 0
1487127030874 D/InteractiveShell: runCommand(...): Command.Result(exitcode=0)
1487127030881 D/MountFactory: Found 25 mounts (normal).
1487127030882 D/MountFactory: Mountpoint(path=/mnt/shell/emulated, blockDevice=tmpfs, fileSystemType=TMPFS, options=[mode=700, nodev, seclabel, relatime, rw, nosuid])
1487127030882 D/MountFactory: Mountpoint(path=/mnt/obb, blockDevice=tmpfs, fileSystemType=TMPFS, options=[seclabel, relatime, rw, gid=1000, mode=755])
1487127030883 D/MountFactory: Mountpoint(path=/protect_s, blockDevice=/emmc@protect_s, fileSystemType=EXT4, options=[data=ordered, nodev, seclabel, rw, nodelalloc, noatime, nosuid, noauto_da_alloc, commit=1])
1487127030883 D/MountFactory: Mountpoint(path=/sys/fs/selinux, blockDevice=selinuxfs, fileSystemType=UNKNOWN, options=[relatime, rw])
1487127030883 D/MountFactory: Mountpoint(path=/, blockDevice=rootfs, fileSystemType=ROOTFS, options=[seclabel, ro])
1487127030884 D/MountFactory: Mountpoint(path=/storage/emulated, blockDevice=tmpfs, fileSystemType=TMPFS, options=[gid=1028, nodev, seclabel, relatime, rw, mode=751, nosuid])
1487127030884 D/MountFactory: Mountpoint(path=/cache, blockDevice=/emmc@cache, fileSystemType=EXT4, options=[data=ordered, nodev, seclabel, rw, noatime, nosuid, noauto_da_alloc, discard])
1487127030884 D/MountFactory: Mountpoint(path=/data, blockDevice=/emmc@usrdata, fileSystemType=EXT4, options=[data=ordered, nodev, seclabel, rw, noatime, nosuid, noauto_da_alloc, discard])
1487127030885 D/MountFactory: Mountpoint(path=/dev/cpuctl, blockDevice=none, fileSystemType=CGROUP, options=[relatime, rw, cpu])
1487127030885 D/MountFactory: Mountpoint(path=/protect_f, blockDevice=/emmc@protect_f, fileSystemType=EXT4, options=[data=ordered, nodev, seclabel, rw, nodelalloc, noatime, nosuid, noauto_da_alloc, commit=1])
1487127030885 D/MountFactory: Mountpoint(path=/mnt/cd-rom, blockDevice=/dev/block/loop0, fileSystemType=UNKNOWN, options=[ro, relatime])
1487127030885 D/MountFactory: Mountpoint(path=/acct, blockDevice=none, fileSystemType=CGROUP, options=[cpuacct, relatime, rw])
1487127030886 D/MountFactory: Mountpoint(path=/dev/pts, blockDevice=devpts, fileSystemType=DEVPTS, options=[seclabel, relatime, rw, mode=600])
1487127030886 D/MountFactory: Mountpoint(path=/storage/emulated/legacy, blockDevice=/dev/fuse, fileSystemType=FUSE, options=[nodev, group_id=1023, relatime, rw, nosuid, default_permissions, allow_other, user_id=1023, noexec])
1487127030886 D/MountFactory: Mountpoint(path=/mnt/media_rw/sdcard1, blockDevice=/dev/block/vold/179:129, fileSystemType=VFAT, options=[nosuid, dirsync, shortname=mixed, gid=1023, allow_utime=0020, dmask=0007, utf8, nodev, relatime, rw, iocharset=iso8859-1, errors=remount-ro, codepage=437, noexec, fmask=0007, uid=1023])
1487127030887 D/MountFactory: Mountpoint(path=/mnt/asec, blockDevice=tmpfs, fileSystemType=TMPFS, options=[seclabel, relatime, rw, gid=1000, mode=755])
1487127030887 D/MountFactory: Mountpoint(path=/sys/kernel/debug, blockDevice=debugfs, fileSystemType=DEBUGFS, options=[seclabel, relatime, rw])
1487127030887 D/MountFactory: Mountpoint(path=/sys, blockDevice=sysfs, fileSystemType=SYSFS, options=[seclabel, relatime, rw])
1487127030887 D/MountFactory: Mountpoint(path=/dev/usb-ffs/adb, blockDevice=adb, fileSystemType=UNKNOWN, options=[relatime, rw])
1487127030888 D/MountFactory: Mountpoint(path=/system, blockDevice=/emmc@android, fileSystemType=EXT4, options=[data=ordered, seclabel, ro, relatime])
1487127030888 D/MountFactory: Mountpoint(path=/proc, blockDevice=proc, fileSystemType=PROC, options=[relatime, rw])
1487127030888 D/MountFactory: Mountpoint(path=/dev, blockDevice=tmpfs, fileSystemType=TMPFS, options=[seclabel, relatime, rw, nosuid, mode=755])
1487127030888 D/MountFactory: Mountpoint(path=/storage/sdcard1, blockDevice=/dev/fuse, fileSystemType=FUSE, options=[nodev, group_id=1023, relatime, rw, nosuid, default_permissions, allow_other, user_id=1023, noexec])
1487127030888 D/MountFactory: Mountpoint(path=/sys/fs/cgroup, blockDevice=none, fileSystemType=TMPFS, options=[seclabel, relatime, rw, gid=1000, mode=750])
1487127030889 D/MountFactory: Mountpoint(path=/storage/emulated/0, blockDevice=/dev/fuse, fileSystemType=FUSE, options=[nodev, group_id=1023, relatime, rw, nosuid, default_permissions, allow_other, user_id=1023, noexec])
1487127030892 V/FileOpsHelper: Looking up mountpoint for:/storage/emulated/0
1487127030892 V/FileOpsHelper: Mount point is:/storage/emulated/0
1487127030896 D/SdcardModule: getExternalCacheDirs(): {/storage/emulated/0/Android/data/eu.thedarken.sdm/cache, /storage/sdcard1/Android/data/eu.thedarken.sdm/cache}
1487127030897 V/FileOpsHelper: Looking up mountpoint for:/storage/sdcard1
1487127030897 V/FileOpsHelper: Mount point is:/storage/sdcard1
1487127030898 D/SdcardModule: EXTERNAL_STORAGE2=null
1487127030899 D/SdcardModule: EXTERNAL_ALT_STORAGE=null
1487127030899 D/SdcardModule: SECOND_VOLUME_STORAGE=null
1487127030899 D/SdcardModule: SECONDARY_STORAGE=/storage/sdcard1
1487127030905 V/FileOpsHelper: Looking up mountpoint for:/system/app
1487127030905 V/FileOpsHelper: Mount point is:/system
1487127030905 V/FileOpsHelper: Looking up mountpoint for:/system/priv-app
1487127030906 V/FileOpsHelper: Mount point is:/system
1487127030906 V/FileOpsHelper: Looking up mountpoint for:/system
1487127030906 V/FileOpsHelper: Mount point is:/system
1487127030906 V/FileOpsHelper: Looking up mountpoint for:/data
1487127030906 V/FileOpsHelper: Mount point is:/data
1487127030907 V/FileOpsHelper: Looking up mountpoint for:/system/vendor
1487127030907 V/FileOpsHelper: Mount point is:/system
1487127030907 V/FileOpsHelper: Looking up mountpoint for:/oem
1487127030907 V/FileOpsHelper: Mount point is:/
1487127030908 I/SDMContext: Initialising StorageVolumeMapper
1487127030912 D/StorageVolumeMapper: Updating mappings.
1487127030928 V/InteractiveShell: Input : exit

1487127030930 D/InteractiveShell: Closed (globalexitcode=0)
1487127030931 I/StorageManager: Detected storages areas:
1487127030931 I/StorageManager: Storage(location=VENDOR, path=/vendor, userHandle=-1, flags=[], safUri=null, mount=Mountpoint(path=/system, blockDevice=/emmc@android, fileSystemType=EXT4, options=[data=ordered, seclabel, ro, relatime]))
1487127030931 I/StorageManager: Storage(location=OEM, path=/oem, userHandle=-1, flags=[], safUri=null, mount=Mountpoint(path=/, blockDevice=rootfs, fileSystemType=ROOTFS, options=[seclabel, ro]))
1487127030932 I/StorageManager: Storage(location=SDCARD, path=/storage/sdcard1, userHandle=-1, flags=[SECONDARY], safUri=null, mount=Mountpoint(path=/storage/sdcard1, blockDevice=/dev/fuse, fileSystemType=FUSE, options=[nodev, group_id=1023, relatime, rw, nosuid, default_permissions, allow_other, user_id=1023, noexec]))
1487127030932 I/StorageManager: Storage(location=SDCARD, path=/storage/emulated/0, userHandle=0, flags=[EMULATED, PRIMARY], safUri=null, mount=Mountpoint(path=/storage/emulated/0, blockDevice=/dev/fuse, fileSystemType=FUSE, options=[nodev, group_id=1023, relatime, rw, nosuid, default_permissions, allow_other, user_id=1023, noexec]))
1487127030932 I/StorageManager: Storage(location=PUBLIC_DATA, path=/storage/emulated/0/Android/data, userHandle=0, flags=[EMULATED, PRIMARY], safUri=null, mount=Mountpoint(path=/storage/emulated/0, blockDevice=/dev/fuse, fileSystemType=FUSE, options=[nodev, group_id=1023, relatime, rw, nosuid, default_permissions, allow_other, user_id=1023, noexec]))
1487127030932 I/StorageManager: Storage(location=PUBLIC_DATA, path=/storage/sdcard1/Android/data, userHandle=-1, flags=[SECONDARY], safUri=null, mount=Mountpoint(path=/storage/sdcard1, blockDevice=/dev/fuse, fileSystemType=FUSE, options=[nodev, group_id=1023, relatime, rw, nosuid, default_permissions, allow_other, user_id=1023, noexec]))
1487127030933 I/StorageManager: Storage(location=SYSTEM, path=/system, userHandle=-1, flags=[PRIMARY], safUri=null, mount=Mountpoint(path=/system, blockDevice=/emmc@android, fileSystemType=EXT4, options=[data=ordered, seclabel, ro, relatime]))
1487127030933 I/StorageManager: Storage(location=PUBLIC_OBB, path=/storage/sdcard1/Android/obb, userHandle=-1, flags=[SECONDARY], safUri=null, mount=Mountpoint(path=/storage/sdcard1, blockDevice=/dev/fuse, fileSystemType=FUSE, options=[nodev, group_id=1023, relatime, rw, nosuid, default_permissions, allow_other, user_id=1023, noexec]))
1487127030933 I/StorageManager: Storage(location=PUBLIC_OBB, path=/storage/emulated/0/Android/obb, userHandle=0, flags=[EMULATED, PRIMARY], safUri=null, mount=Mountpoint(path=/storage/emulated/0, blockDevice=/dev/fuse, fileSystemType=FUSE, options=[nodev, group_id=1023, relatime, rw, nosuid, default_permissions, allow_other, user_id=1023, noexec]))
1487127030933 I/StorageManager: Storage(location=SYSTEM_PRIV_APP, path=/system/priv-app, userHandle=-1, flags=[], safUri=null, mount=Mountpoint(path=/system, blockDevice=/emmc@android, fileSystemType=EXT4, options=[data=ordered, seclabel, ro, relatime]))
1487127030934 I/StorageManager: Storage(location=PUBLIC_MEDIA, path=/storage/sdcard1/Android/media, userHandle=-1, flags=[SECONDARY], safUri=null, mount=Mountpoint(path=/storage/sdcard1, blockDevice=/dev/fuse, fileSystemType=FUSE, options=[nodev, group_id=1023, relatime, rw, nosuid, default_permissions, allow_other, user_id=1023, noexec]))
1487127030934 I/StorageManager: Storage(location=PUBLIC_MEDIA, path=/storage/emulated/0/Android/media, userHandle=0, flags=[EMULATED, PRIMARY], safUri=null, mount=Mountpoint(path=/storage/emulated/0, blockDevice=/dev/fuse, fileSystemType=FUSE, options=[nodev, group_id=1023, relatime, rw, nosuid, default_permissions, allow_other, user_id=1023, noexec]))
1487127030934 I/StorageManager: Storage(location=SYSTEM_APP, path=/system/app, userHandle=-1, flags=[], safUri=null, mount=Mountpoint(path=/system, blockDevice=/emmc@android, fileSystemType=EXT4, options=[data=ordered, seclabel, ro, relatime]))
1487127030934 I/StorageManager: Storage(location=DATA, path=/data, userHandle=-1, flags=[PRIMARY], safUri=null, mount=Mountpoint(path=/data, blockDevice=/emmc@usrdata, fileSystemType=EXT4, options=[data=ordered, nodev, seclabel, rw, noatime, nosuid, noauto_da_alloc, discard]))
1487127030936 D/StorageAccessFragment: WRITE_EXTERNAL_STORAGE permission has already been granted. Progressing...
````

**Comment by d4rken** [comment]
Lack of infos, can't reproduce. I'd basically need this exact device to work on it :(.
