### ISSUE TITLE
Android O: /system/build.prop can't be read

### ISSUE THREAD

**Issue by d4rken** [d4rken/sdmaid-public#833]
Check if there is an alternative way to get some more ROM infos.

Could probably test this on the emulator.

```
1491768494068 E/Debug: java.io.FileNotFoundException: /system/build.prop (Permission denied)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:200)
	at java.io.FileInputStream.<init>(FileInputStream.java:150)
	at java.io.FileReader.<init>(FileReader.java:72)
	at eu.thedarken.sdm.f.e(SDMDebug.java:71)
	at eu.thedarken.sdm.f.d(SDMDebug.java:157)
	at eu.thedarken.sdm.g.run(Unknown Source:0)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by Moozart** [comment]
Are there any fix method?

**Comment by d4rken** [comment]
No, not without root, for SD Maids purpose similar debug output is now accessed from the API via `Build...`.

**Comment by Moozart** [comment]
I am using system uid app. But I getting this error on Android 8. No problem on Android Nougat
