### ISSUE TITLE
FC when selecting Permission Changes

### ISSUE THREAD

**Issue by noc-jfcbs** [d4rken/sdmaid-public#881]
[2017-05-11-09-06-40.txt](https://github.com/d4rken/sdmaid-public/files/992196/2017-05-11-09-06-40.txt)
[sdmaid_logfile_1494486412970.txt](https://github.com/d4rken/sdmaid-public/files/992202/sdmaid_logfile_1494486412970.txt)

- Samsung Galaxy S3 LTE (GT-i9305)
- Resurrection Remix N-v5.8.3
- Rooted with Magisk v12
- SD Maid Pro v4.6.5 (40605), Unlocker v4.0.13 (40013), Experimental Mode: True
- Install-ID: 68c40173-4ea6-4fcb-afb7-fdaa098853da
- Error reporting enabled

When trying to change permissions of a folder or file located either in internal storage or root, SD Maid always forcely closes as soon as tapping on "Change Permissions".

I hope the error report was sent. Please advise in case of further questions or if a log / logcat is required.

**Comment by d4rken** [comment]
Under the install ID i can only find a crash from `1 day agoMay 9th, 10:07:26 UTC` which seems to be related to UI elements from the Activity Manager.

Just by device specs I could narrow it down to a couple of crashes but nothing from the explorer tool.
We'll need log. A debug run log be sufficient, but it's still weird that no automatic report was received for this.

**Comment by noc-jfcbs** [comment]
Logcat and SD Maid Log added to 1st post. While taking the log, the device was online, and I hope an automatic report was sent this time.
Please advise if further information is required.

**Comment by noc-jfcbs** [comment]
Hallo Matthias,

ich habe sowohl ein SD Maid Log als auch ein Logcat dem 1. Post beigefügt. Hoffe, sie sind aussagekräftig.

 

Lieben Gruß nach Aachen aus dem Selfkant.

Schmidy

 

Von: Matthias Urhahn [mailto:notifications@github.com] 
Gesendet: Mittwoch, 10. Mai 2017 23:08
An: d4rken/sdmaid-public <sdmaid-public@noreply.github.com>
Cc: noc-jfcbs <airforceone@posteo.de>; Author <author@noreply.github.com>
Betreff: Re: [d4rken/sdmaid-public] FC when selecting Permission Changes (#881)

 

Under the install ID i can only find a crash from 1 day agoMay 9th, 10:07:26 UTC which seems to be related to UI elements from the Activity Manager.

Just by device specs I could narrow it down to a couple of crashes but nothing from the explorer tool.
We'll need log. A debug run log be sufficient, but it's still weird that no automatic report was received for this.

**Comment by d4rken** [comment]
The automatic crash reports were working afterall. The crash just seems to be unrelated to permission changing which is why I overlooked it.

Seems to be a UI bug and no code from SD Maid is part of the stacktrace.

```
java.lang.IndexOutOfBoundsException
        at android.graphics.Paint.getRunAdvance(Paint.java:2557)
        at android.text.TextLine.handleText(TextLine.java:719)
        at android.text.TextLine.handleRun(TextLine.java:869)
        at android.text.TextLine.measureRun(TextLine.java:387)
        at android.text.TextLine.measure(TextLine.java:277)
        at android.text.TextLine.metrics(TextLine.java:251)
        at android.text.Layout.getLineExtent(Layout.java:1067)
        at android.text.Layout.getLineWidth(Layout.java:1033)
        at android.widget.TextView.desired(TextView.java:7004)
        at android.widget.TextView.onMeasure(TextView.java:7070)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.support.v7.widget.LinearLayoutCompat.measureChildBeforeLayout(LinearLayoutCompat.java:1377)
        at android.support.v7.widget.LinearLayoutCompat.measureVertical(LinearLayoutCompat.java:660)
        at android.support.v7.widget.LinearLayoutCompat.onMeasure(LinearLayoutCompat.java:551)
        at android.support.v7.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:65)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:692)
        at android.view.View.measure(View.java:19861)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2023)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6178)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

**Comment by noc-jfcbs** [comment]
Might it be 'cause I commenced using Substratum together with a theme of the main dev of my ROM (Pitchblack by westcrip)?
I'm going to disable the theme and try to reproduce; also to freeze Substratum and try to reproduce.
Reporting back.

**Comment by d4rken** [comment]
For my reference: https://app.bugsnag.com/darken-development/sd-maid/errors/585eb0391eecd39ad90a71ec

The same crash can be seen on multiple devices (6P, A3003, i9305, Redmi Note4, Nexus 6) but only on Android 7.11 or 7.1.2.

Searching for this errors brings up a bunch of solutions, but none of them seem to apply here.

**Comment by noc-jfcbs** [comment]
I can confirm, no issues after uninstall of the theme overlays; Substratum remained installed.
And I don't wonder that it only occurs with Android 7.1.1 or 7.1.2 as the issue is certainly connected to the way how the overlays are built by Substratum. I'm convinced it isn't device related but only occurs on Android 7.1.1 or 7.1.2 ROMs that support Substratum; not all such ROM do.

**Comment by d4rken** [comment]
Not much I can do from my side then. Nice to have this written up though, maybe it helps other users searching for such an issue.
